import os from "os";
import path from "path";
import type { ProjectConfig } from "../../types";
import { CLAUDE_SRC_DIR, STANDARD_FILES } from "../../consts";
import { fileExists, ensureDir, writeFile } from "../../utils/fs";
import { verbose } from "../../utils/logger";
import { compactStackForYaml } from "./config-generator";
import { PROJECT_CONFIG_INTERFACE_TEMPLATE } from "./config-types-writer";

export type ConfigSourceOptions = {
  /**
   * When true, generates a project config that imports and extends the global config.
   * The global config import path is resolved internally via `getGlobalConfigImportPath()`.
   */
  isProjectConfig?: boolean;
};

/**
 * Generates a TypeScript config file source from a ProjectConfig object.
 * Output is a plain object literal with `satisfies ProjectConfig` for type safety.
 *
 * When `options.isProjectConfig` is true, the generated config imports from the global
 * config and spreads global arrays into skills, agents, and domains.
 */
export function generateConfigSource(config: ProjectConfig, options?: ConfigSourceOptions): string {
  const serializable = config.stack
    ? { ...config, stack: compactStackForYaml(config.stack) }
    : { ...config };

  // JSON.parse(JSON.stringify(x)) removes undefined values
  const cleaned = JSON.parse(JSON.stringify(serializable));

  if (options?.isProjectConfig) {
    return generateProjectConfigWithGlobalImport(cleaned, getGlobalConfigImportPath());
  }

  const body = JSON.stringify(cleaned, null, 2);

  return [
    `import type { ProjectConfig } from "./config-types";`,
    ``,
    `export default ${body} satisfies ProjectConfig;`,
    ``,
  ].join("\n");
}

/**
 * Generates a project config source that imports from the global config and extends it.
 * Arrays (skills, agents, domains) are spread with globalConfig first, then project items.
 */
function generateProjectConfigWithGlobalImport(
  cleaned: Record<string, unknown>,
  globalImportPath: string,
): string {
  const importPath = `${globalImportPath}/config`;

  // Boundary cast: cleaned comes from JSON.parse(JSON.stringify(...)) so arrays are plain JSON values
  const skillItems = ((cleaned.skills as unknown[]) ?? [])
    .map((s) => `    ${JSON.stringify(s)},`)
    .join("\n");
  const agentItems = ((cleaned.agents as unknown[]) ?? [])
    .map((a) => `    ${JSON.stringify(a)},`)
    .join("\n");

  const domainsBlock = cleaned.domains
    ? `  domains: [...(globalConfig.domains ?? []),\n${(cleaned.domains as unknown[]).map((d) => `    ${JSON.stringify(d)},`).join("\n")}\n  ],`
    : "";

  const arrayFields = new Set(["skills", "agents", "domains", "name"]);
  const scalarFields = Object.entries(cleaned)
    .filter(([key]) => !arrayFields.has(key))
    .map(([key, value]) => `  ${JSON.stringify(key)}: ${JSON.stringify(value)},`)
    .join("\n");

  const tail =
    (domainsBlock ? `${domainsBlock}\n` : "") + (scalarFields ? `${scalarFields}\n` : "");

  return `import globalConfig from "${importPath}";
import type { ProjectConfig } from "./config-types";

export default {
  ...globalConfig,
${cleaned.name ? `  name: ${JSON.stringify(cleaned.name)},\n` : ""}  skills: [
    ...globalConfig.skills,
${skillItems ? `${skillItems}\n` : ""}  ],
  agents: [
    ...globalConfig.agents,
${agentItems ? `${agentItems}\n` : ""}  ],
${tail}} satisfies ProjectConfig;
`;
}

/**
 * Returns the absolute path to the global .claude-src directory.
 * Used as the import path for project configs that extend global.
 */
export function getGlobalConfigImportPath(): string {
  return path.join(os.homedir(), CLAUDE_SRC_DIR);
}

/**
 * Generates a blank global config source (empty arrays, no import preamble).
 */
export function generateBlankGlobalConfigSource(): string {
  return `import type { ProjectConfig } from "./config-types";

export default {
  "name": "global",
  "skills": [],
  "agents": [],
  "domains": []
} satisfies ProjectConfig;\n`;
}

/**
 * Generates blank global config-types source (all types are `never`).
 */
export function generateBlankGlobalConfigTypesSource(): string {
  return `// AUTO-GENERATED by agentsinc — DO NOT EDIT

export type SkillId = never;

export type AgentName = never;

export type Domain = never;

export type Category = never;

${PROJECT_CONFIG_INTERFACE_TEMPLATE}`;
}

/**
 * Ensures a blank global config exists at ~/.claude-src/.
 * Creates config.ts (empty arrays) and config-types.ts (never types) if they don't exist.
 * Returns true if files were created, false if they already existed.
 */
export async function ensureBlankGlobalConfig(): Promise<boolean> {
  const globalConfigDir = path.join(os.homedir(), CLAUDE_SRC_DIR);
  const configPath = path.join(globalConfigDir, STANDARD_FILES.CONFIG_TS);

  if (await fileExists(configPath)) {
    verbose("Global config already exists, skipping blank creation");
    return false;
  }

  await ensureDir(globalConfigDir);

  const configSource = generateBlankGlobalConfigSource();
  const typesSource = generateBlankGlobalConfigTypesSource();

  await writeFile(configPath, configSource);
  await writeFile(path.join(globalConfigDir, STANDARD_FILES.CONFIG_TYPES_TS), typesSource);

  verbose(`Created blank global config at ${globalConfigDir}`);
  return true;
}
