import type { SkillAssignment, Stack } from "../../types";

/**
 * Built-in stack definitions, equivalent to config/stacks.ts.
 * Source repos may override or extend these via their own stacks files.
 *
 * All values are already in normalized form (SkillAssignment[] with { id, preloaded }).
 */

const SHARED_TOOLING: SkillAssignment[] = [
  { id: "shared-tooling-eslint-prettier", preloaded: false },
  { id: "shared-tooling-typescript-config", preloaded: false },
  { id: "shared-tooling-git-hooks", preloaded: false },
];

export const defaultStacks: Stack[] = [
  {
    id: "nextjs-fullstack",
    name: "Next.js Fullstack",
    description: "Next.js + Hono full-stack",
    philosophy: "Ship fast, iterate faster",
    agents: {
      "web-developer": {
        "web-framework": [{ id: "web-framework-react", preloaded: true }],
        "web-meta-framework": [{ id: "web-meta-framework-nextjs", preloaded: true }],
        "web-styling": [{ id: "web-styling-scss-modules", preloaded: false }],
        "web-client-state": [{ id: "web-state-zustand", preloaded: false }],
        "web-server-state": [{ id: "web-server-state-react-query", preloaded: false }],
        "web-testing": [{ id: "web-testing-vitest", preloaded: false }],
        "web-mocking": [{ id: "web-mocks-msw", preloaded: false }],
        "web-accessibility": [{ id: "web-accessibility-web-accessibility", preloaded: false }],
        "shared-tooling": SHARED_TOOLING,
        "web-tooling": [{ id: "web-tooling-vite", preloaded: false }],
      },
      "api-developer": {
        "api-api": [{ id: "api-framework-hono", preloaded: true }],
        "api-database": [{ id: "api-database-drizzle", preloaded: true }],
        "api-auth": [{ id: "api-auth-better-auth-drizzle-hono", preloaded: false }],
        "api-observability": [{ id: "api-observability-axiom-pino-sentry", preloaded: false }],
        "api-analytics": [{ id: "api-analytics-posthog-analytics", preloaded: false }],
        "api-email": [{ id: "api-email-resend-react-email", preloaded: false }],
        "shared-ci-cd": [{ id: "shared-ci-cd-github-actions", preloaded: false }],
        "shared-tooling": SHARED_TOOLING,
      },
      "cli-developer": {
        "cli-framework": [{ id: "cli-framework-cli-commander", preloaded: true }],
        "shared-tooling": SHARED_TOOLING,
      },
      "web-reviewer": {
        "shared-meta": [{ id: "shared-meta-reviewing", preloaded: true }],
        "web-framework": [{ id: "web-framework-react", preloaded: false }],
        "web-meta-framework": [{ id: "web-meta-framework-nextjs", preloaded: false }],
        "web-styling": [{ id: "web-styling-scss-modules", preloaded: false }],
        "web-client-state": [{ id: "web-state-zustand", preloaded: false }],
        "web-server-state": [{ id: "web-server-state-react-query", preloaded: false }],
        "web-testing": [{ id: "web-testing-vitest", preloaded: false }],
        "web-mocking": [{ id: "web-mocks-msw", preloaded: false }],
      },
      "api-reviewer": {
        "shared-meta": [{ id: "shared-meta-reviewing", preloaded: true }],
        "api-api": [{ id: "api-framework-hono", preloaded: false }],
        "api-database": [{ id: "api-database-drizzle", preloaded: false }],
        "api-auth": [{ id: "api-auth-better-auth-drizzle-hono", preloaded: false }],
        "api-observability": [{ id: "api-observability-axiom-pino-sentry", preloaded: false }],
      },
      "cli-reviewer": {
        "shared-meta": [{ id: "shared-meta-cli-reviewing", preloaded: true }],
        "cli-framework": [{ id: "cli-framework-cli-commander", preloaded: false }],
      },
      "web-tester": {
        "web-testing": [
          { id: "web-testing-playwright-e2e", preloaded: false },
          { id: "web-testing-vitest", preloaded: false },
        ],
        "web-mocking": [{ id: "web-mocks-msw", preloaded: false }],
      },
      "web-pm": {
        "web-framework": [{ id: "web-framework-react", preloaded: false }],
        "web-meta-framework": [{ id: "web-meta-framework-nextjs", preloaded: false }],
        "web-styling": [{ id: "web-styling-scss-modules", preloaded: false }],
        "web-client-state": [{ id: "web-state-zustand", preloaded: false }],
        "web-server-state": [{ id: "web-server-state-react-query", preloaded: false }],
        "web-testing": [{ id: "web-testing-vitest", preloaded: false }],
        "web-mocking": [{ id: "web-mocks-msw", preloaded: false }],
        "web-accessibility": [{ id: "web-accessibility-web-accessibility", preloaded: false }],
        "api-api": [{ id: "api-framework-hono", preloaded: false }],
        "api-database": [{ id: "api-database-drizzle", preloaded: false }],
        "api-auth": [{ id: "api-auth-better-auth-drizzle-hono", preloaded: false }],
        "api-observability": [{ id: "api-observability-axiom-pino-sentry", preloaded: false }],
        "api-analytics": [{ id: "api-analytics-posthog-analytics", preloaded: false }],
        "api-email": [{ id: "api-email-resend-react-email", preloaded: false }],
        "shared-ci-cd": [{ id: "shared-ci-cd-github-actions", preloaded: false }],
        "cli-framework": [{ id: "cli-framework-cli-commander", preloaded: false }],
      },
      "web-architecture": {
        "api-api": [{ id: "api-framework-hono", preloaded: false }],
        "api-database": [{ id: "api-database-drizzle", preloaded: false }],
        "api-auth": [{ id: "api-auth-better-auth-drizzle-hono", preloaded: false }],
        "api-observability": [{ id: "api-observability-axiom-pino-sentry", preloaded: false }],
        "api-analytics": [{ id: "api-analytics-posthog-analytics", preloaded: false }],
        "api-email": [{ id: "api-email-resend-react-email", preloaded: false }],
        "shared-ci-cd": [{ id: "shared-ci-cd-github-actions", preloaded: false }],
        "cli-framework": [{ id: "cli-framework-cli-commander", preloaded: false }],
      },
      "web-researcher": {
        "web-framework": [{ id: "web-framework-react", preloaded: false }],
        "web-meta-framework": [{ id: "web-meta-framework-nextjs", preloaded: false }],
        "web-styling": [{ id: "web-styling-scss-modules", preloaded: false }],
        "web-client-state": [{ id: "web-state-zustand", preloaded: false }],
        "web-server-state": [{ id: "web-server-state-react-query", preloaded: false }],
        "web-testing": [{ id: "web-testing-vitest", preloaded: false }],
        "web-mocking": [{ id: "web-mocks-msw", preloaded: false }],
        "web-accessibility": [{ id: "web-accessibility-web-accessibility", preloaded: false }],
      },
      "api-researcher": {
        "api-api": [{ id: "api-framework-hono", preloaded: false }],
        "api-database": [{ id: "api-database-drizzle", preloaded: false }],
        "api-auth": [{ id: "api-auth-better-auth-drizzle-hono", preloaded: false }],
        "api-observability": [{ id: "api-observability-axiom-pino-sentry", preloaded: false }],
        "api-analytics": [{ id: "api-analytics-posthog-analytics", preloaded: false }],
        "api-email": [{ id: "api-email-resend-react-email", preloaded: false }],
        "shared-ci-cd": [{ id: "shared-ci-cd-github-actions", preloaded: false }],
        "cli-framework": [{ id: "cli-framework-cli-commander", preloaded: false }],
      },
      "pattern-scout": {
        "web-framework": [{ id: "web-framework-react", preloaded: false }],
        "web-meta-framework": [{ id: "web-meta-framework-nextjs", preloaded: false }],
        "web-styling": [{ id: "web-styling-scss-modules", preloaded: false }],
        "web-client-state": [{ id: "web-state-zustand", preloaded: false }],
        "web-server-state": [{ id: "web-server-state-react-query", preloaded: false }],
        "web-testing": [{ id: "web-testing-vitest", preloaded: false }],
        "web-mocking": [{ id: "web-mocks-msw", preloaded: false }],
        "web-accessibility": [{ id: "web-accessibility-web-accessibility", preloaded: false }],
        "api-api": [{ id: "api-framework-hono", preloaded: false }],
        "api-database": [{ id: "api-database-drizzle", preloaded: false }],
        "api-auth": [{ id: "api-auth-better-auth-drizzle-hono", preloaded: false }],
        "api-observability": [{ id: "api-observability-axiom-pino-sentry", preloaded: false }],
        "api-analytics": [{ id: "api-analytics-posthog-analytics", preloaded: false }],
        "api-email": [{ id: "api-email-resend-react-email", preloaded: false }],
        "shared-ci-cd": [{ id: "shared-ci-cd-github-actions", preloaded: false }],
      },
      "web-pattern-critique": {
        "web-framework": [{ id: "web-framework-react", preloaded: false }],
        "web-meta-framework": [{ id: "web-meta-framework-nextjs", preloaded: false }],
        "web-styling": [{ id: "web-styling-scss-modules", preloaded: false }],
        "web-client-state": [{ id: "web-state-zustand", preloaded: false }],
        "web-server-state": [{ id: "web-server-state-react-query", preloaded: false }],
        "web-testing": [{ id: "web-testing-vitest", preloaded: false }],
        "web-mocking": [{ id: "web-mocks-msw", preloaded: false }],
        "web-accessibility": [{ id: "web-accessibility-web-accessibility", preloaded: false }],
        "api-api": [{ id: "api-framework-hono", preloaded: false }],
        "api-database": [{ id: "api-database-drizzle", preloaded: false }],
        "api-auth": [{ id: "api-auth-better-auth-drizzle-hono", preloaded: false }],
        "api-observability": [{ id: "api-observability-axiom-pino-sentry", preloaded: false }],
        "api-analytics": [{ id: "api-analytics-posthog-analytics", preloaded: false }],
        "api-email": [{ id: "api-email-resend-react-email", preloaded: false }],
        "shared-ci-cd": [{ id: "shared-ci-cd-github-actions", preloaded: false }],
        "shared-meta": [{ id: "shared-meta-reviewing", preloaded: true }],
      },
      "agent-summoner": {
        "web-framework": [{ id: "web-framework-react", preloaded: false }],
        "web-meta-framework": [{ id: "web-meta-framework-nextjs", preloaded: false }],
        "web-styling": [{ id: "web-styling-scss-modules", preloaded: false }],
        "web-client-state": [{ id: "web-state-zustand", preloaded: false }],
        "web-server-state": [{ id: "web-server-state-react-query", preloaded: false }],
        "web-testing": [{ id: "web-testing-vitest", preloaded: false }],
        "web-mocking": [{ id: "web-mocks-msw", preloaded: false }],
        "web-accessibility": [{ id: "web-accessibility-web-accessibility", preloaded: false }],
        "api-api": [{ id: "api-framework-hono", preloaded: false }],
        "api-database": [{ id: "api-database-drizzle", preloaded: false }],
        "api-auth": [{ id: "api-auth-better-auth-drizzle-hono", preloaded: false }],
        "api-observability": [{ id: "api-observability-axiom-pino-sentry", preloaded: false }],
        "api-analytics": [{ id: "api-analytics-posthog-analytics", preloaded: false }],
        "api-email": [{ id: "api-email-resend-react-email", preloaded: false }],
        "shared-ci-cd": [{ id: "shared-ci-cd-github-actions", preloaded: false }],
        "cli-framework": [{ id: "cli-framework-cli-commander", preloaded: false }],
        "shared-meta": [{ id: "shared-meta-reviewing", preloaded: false }],
      },
      "skill-summoner": {
        "web-framework": [{ id: "web-framework-react", preloaded: false }],
        "web-meta-framework": [{ id: "web-meta-framework-nextjs", preloaded: false }],
        "web-styling": [{ id: "web-styling-scss-modules", preloaded: false }],
        "web-client-state": [{ id: "web-state-zustand", preloaded: false }],
        "web-server-state": [{ id: "web-server-state-react-query", preloaded: false }],
        "web-testing": [{ id: "web-testing-vitest", preloaded: false }],
        "web-mocking": [{ id: "web-mocks-msw", preloaded: false }],
        "web-accessibility": [{ id: "web-accessibility-web-accessibility", preloaded: false }],
        "api-api": [{ id: "api-framework-hono", preloaded: false }],
        "api-database": [{ id: "api-database-drizzle", preloaded: false }],
        "api-auth": [{ id: "api-auth-better-auth-drizzle-hono", preloaded: false }],
        "api-observability": [{ id: "api-observability-axiom-pino-sentry", preloaded: false }],
        "api-analytics": [{ id: "api-analytics-posthog-analytics", preloaded: false }],
        "api-email": [{ id: "api-email-resend-react-email", preloaded: false }],
        "shared-ci-cd": [{ id: "shared-ci-cd-github-actions", preloaded: false }],
        "cli-framework": [{ id: "cli-framework-cli-commander", preloaded: false }],
        "shared-meta": [{ id: "shared-meta-reviewing", preloaded: false }],
      },
      documentor: {
        "web-framework": [{ id: "web-framework-react", preloaded: false }],
        "web-meta-framework": [{ id: "web-meta-framework-nextjs", preloaded: false }],
        "web-styling": [{ id: "web-styling-scss-modules", preloaded: false }],
        "web-client-state": [{ id: "web-state-zustand", preloaded: false }],
        "web-server-state": [{ id: "web-server-state-react-query", preloaded: false }],
        "web-testing": [{ id: "web-testing-vitest", preloaded: false }],
        "web-mocking": [{ id: "web-mocks-msw", preloaded: false }],
        "web-accessibility": [{ id: "web-accessibility-web-accessibility", preloaded: false }],
        "api-api": [{ id: "api-framework-hono", preloaded: false }],
        "api-database": [{ id: "api-database-drizzle", preloaded: false }],
        "api-auth": [{ id: "api-auth-better-auth-drizzle-hono", preloaded: false }],
        "api-observability": [{ id: "api-observability-axiom-pino-sentry", preloaded: false }],
        "api-analytics": [{ id: "api-analytics-posthog-analytics", preloaded: false }],
        "api-email": [{ id: "api-email-resend-react-email", preloaded: false }],
        "shared-ci-cd": [{ id: "shared-ci-cd-github-actions", preloaded: false }],
        "cli-framework": [{ id: "cli-framework-cli-commander", preloaded: false }],
        "shared-meta": [{ id: "shared-meta-reviewing", preloaded: false }],
      },
      "cli-tester": {},
    },
  },
  {
    id: "angular-stack",
    name: "Modern Angular Stack",
    description: "Angular + Signals stack",
    philosophy: "Enterprise-grade and type-safe",
    agents: {
      "web-developer": {
        "web-framework": [{ id: "web-framework-angular-standalone", preloaded: true }],
        "web-client-state": [{ id: "web-state-ngrx-signalstore", preloaded: false }],
        "web-testing": [{ id: "web-testing-vitest", preloaded: false }],
        "shared-tooling": SHARED_TOOLING,
        "web-tooling": [{ id: "web-tooling-vite", preloaded: false }],
      },
      "api-developer": {
        "api-api": [{ id: "api-framework-hono", preloaded: true }],
        "api-database": [{ id: "api-database-drizzle", preloaded: true }],
        "api-auth": [{ id: "api-auth-better-auth-drizzle-hono", preloaded: false }],
        "api-observability": [{ id: "api-observability-axiom-pino-sentry", preloaded: false }],
        "shared-tooling": SHARED_TOOLING,
      },
      "web-reviewer": {
        "shared-meta": [{ id: "shared-meta-reviewing", preloaded: true }],
        "web-framework": [{ id: "web-framework-angular-standalone", preloaded: false }],
        "web-client-state": [{ id: "web-state-ngrx-signalstore", preloaded: false }],
        "web-testing": [{ id: "web-testing-vitest", preloaded: false }],
      },
      "api-reviewer": {
        "shared-meta": [{ id: "shared-meta-reviewing", preloaded: true }],
        "api-api": [{ id: "api-framework-hono", preloaded: false }],
        "api-database": [{ id: "api-database-drizzle", preloaded: false }],
        "api-auth": [{ id: "api-auth-better-auth-drizzle-hono", preloaded: false }],
        "api-observability": [{ id: "api-observability-axiom-pino-sentry", preloaded: false }],
      },
      "web-pm": {
        "web-framework": [{ id: "web-framework-angular-standalone", preloaded: false }],
        "web-client-state": [{ id: "web-state-ngrx-signalstore", preloaded: false }],
        "web-testing": [{ id: "web-testing-vitest", preloaded: false }],
        "api-api": [{ id: "api-framework-hono", preloaded: false }],
        "api-database": [{ id: "api-database-drizzle", preloaded: false }],
        "api-auth": [{ id: "api-auth-better-auth-drizzle-hono", preloaded: false }],
        "api-observability": [{ id: "api-observability-axiom-pino-sentry", preloaded: false }],
      },
      "web-architecture": {
        "api-api": [{ id: "api-framework-hono", preloaded: false }],
        "api-database": [{ id: "api-database-drizzle", preloaded: false }],
        "api-auth": [{ id: "api-auth-better-auth-drizzle-hono", preloaded: false }],
        "api-observability": [{ id: "api-observability-axiom-pino-sentry", preloaded: false }],
      },
      "web-researcher": {
        "web-framework": [{ id: "web-framework-angular-standalone", preloaded: false }],
        "web-client-state": [{ id: "web-state-ngrx-signalstore", preloaded: false }],
        "web-testing": [{ id: "web-testing-vitest", preloaded: false }],
      },
      "api-researcher": {
        "api-api": [{ id: "api-framework-hono", preloaded: false }],
        "api-database": [{ id: "api-database-drizzle", preloaded: false }],
        "api-auth": [{ id: "api-auth-better-auth-drizzle-hono", preloaded: false }],
        "api-observability": [{ id: "api-observability-axiom-pino-sentry", preloaded: false }],
      },
      "pattern-scout": {
        "web-framework": [{ id: "web-framework-angular-standalone", preloaded: false }],
        "web-client-state": [{ id: "web-state-ngrx-signalstore", preloaded: false }],
        "web-testing": [{ id: "web-testing-vitest", preloaded: false }],
        "api-api": [{ id: "api-framework-hono", preloaded: false }],
        "api-database": [{ id: "api-database-drizzle", preloaded: false }],
        "api-auth": [{ id: "api-auth-better-auth-drizzle-hono", preloaded: false }],
        "api-observability": [{ id: "api-observability-axiom-pino-sentry", preloaded: false }],
      },
      "web-pattern-critique": {
        "web-framework": [{ id: "web-framework-angular-standalone", preloaded: false }],
        "web-client-state": [{ id: "web-state-ngrx-signalstore", preloaded: false }],
        "web-testing": [{ id: "web-testing-vitest", preloaded: false }],
        "api-api": [{ id: "api-framework-hono", preloaded: false }],
        "api-database": [{ id: "api-database-drizzle", preloaded: false }],
        "api-auth": [{ id: "api-auth-better-auth-drizzle-hono", preloaded: false }],
        "api-observability": [{ id: "api-observability-axiom-pino-sentry", preloaded: false }],
        "shared-meta": [{ id: "shared-meta-reviewing", preloaded: true }],
      },
      "agent-summoner": {
        "web-framework": [{ id: "web-framework-angular-standalone", preloaded: false }],
        "web-client-state": [{ id: "web-state-ngrx-signalstore", preloaded: false }],
        "web-testing": [{ id: "web-testing-vitest", preloaded: false }],
        "api-api": [{ id: "api-framework-hono", preloaded: false }],
        "api-database": [{ id: "api-database-drizzle", preloaded: false }],
        "api-auth": [{ id: "api-auth-better-auth-drizzle-hono", preloaded: false }],
        "api-observability": [{ id: "api-observability-axiom-pino-sentry", preloaded: false }],
        "shared-meta": [{ id: "shared-meta-reviewing", preloaded: false }],
      },
      "skill-summoner": {
        "web-framework": [{ id: "web-framework-angular-standalone", preloaded: false }],
        "web-client-state": [{ id: "web-state-ngrx-signalstore", preloaded: false }],
        "web-testing": [{ id: "web-testing-vitest", preloaded: false }],
        "api-api": [{ id: "api-framework-hono", preloaded: false }],
        "api-database": [{ id: "api-database-drizzle", preloaded: false }],
        "api-auth": [{ id: "api-auth-better-auth-drizzle-hono", preloaded: false }],
        "api-observability": [{ id: "api-observability-axiom-pino-sentry", preloaded: false }],
        "shared-meta": [{ id: "shared-meta-reviewing", preloaded: false }],
      },
      documentor: {
        "web-framework": [{ id: "web-framework-angular-standalone", preloaded: false }],
        "web-client-state": [{ id: "web-state-ngrx-signalstore", preloaded: false }],
        "web-testing": [{ id: "web-testing-vitest", preloaded: false }],
        "api-api": [{ id: "api-framework-hono", preloaded: false }],
        "api-database": [{ id: "api-database-drizzle", preloaded: false }],
        "api-auth": [{ id: "api-auth-better-auth-drizzle-hono", preloaded: false }],
        "api-observability": [{ id: "api-observability-axiom-pino-sentry", preloaded: false }],
        "shared-meta": [{ id: "shared-meta-reviewing", preloaded: false }],
      },
      "web-tester": {
        "web-testing": [
          { id: "web-testing-playwright-e2e", preloaded: false },
          { id: "web-testing-vitest", preloaded: false },
        ],
      },
    },
  },
  {
    id: "nuxt-stack",
    name: "Nuxt Full-Stack",
    description: "Vue + Nuxt full-stack",
    philosophy: "Progressive Vue with Nuxt power",
    agents: {
      "web-developer": {
        "web-framework": [{ id: "web-framework-vue-composition-api", preloaded: true }],
        "web-meta-framework": [{ id: "web-meta-framework-nuxt", preloaded: true }],
        "web-client-state": [{ id: "web-state-pinia", preloaded: false }],
        "web-testing": [{ id: "web-testing-vitest", preloaded: false }],
        "shared-tooling": SHARED_TOOLING,
        "web-tooling": [{ id: "web-tooling-vite", preloaded: false }],
      },
      "api-developer": {
        "api-api": [{ id: "api-framework-hono", preloaded: true }],
        "api-database": [{ id: "api-database-drizzle", preloaded: true }],
        "api-auth": [{ id: "api-auth-better-auth-drizzle-hono", preloaded: false }],
        "api-observability": [{ id: "api-observability-axiom-pino-sentry", preloaded: false }],
        "shared-tooling": SHARED_TOOLING,
      },
      "web-reviewer": {
        "shared-meta": [{ id: "shared-meta-reviewing", preloaded: true }],
        "web-framework": [{ id: "web-framework-vue-composition-api", preloaded: false }],
        "web-meta-framework": [{ id: "web-meta-framework-nuxt", preloaded: false }],
        "web-client-state": [{ id: "web-state-pinia", preloaded: false }],
        "web-testing": [{ id: "web-testing-vitest", preloaded: false }],
      },
      "api-reviewer": {
        "shared-meta": [{ id: "shared-meta-reviewing", preloaded: true }],
        "api-api": [{ id: "api-framework-hono", preloaded: false }],
        "api-database": [{ id: "api-database-drizzle", preloaded: false }],
        "api-auth": [{ id: "api-auth-better-auth-drizzle-hono", preloaded: false }],
        "api-observability": [{ id: "api-observability-axiom-pino-sentry", preloaded: false }],
      },
      "web-pm": {
        "web-framework": [{ id: "web-framework-vue-composition-api", preloaded: false }],
        "web-meta-framework": [{ id: "web-meta-framework-nuxt", preloaded: false }],
        "web-client-state": [{ id: "web-state-pinia", preloaded: false }],
        "web-testing": [{ id: "web-testing-vitest", preloaded: false }],
        "api-api": [{ id: "api-framework-hono", preloaded: false }],
        "api-database": [{ id: "api-database-drizzle", preloaded: false }],
        "api-auth": [{ id: "api-auth-better-auth-drizzle-hono", preloaded: false }],
        "api-observability": [{ id: "api-observability-axiom-pino-sentry", preloaded: false }],
      },
      "web-architecture": {
        "api-api": [{ id: "api-framework-hono", preloaded: false }],
        "api-database": [{ id: "api-database-drizzle", preloaded: false }],
        "api-auth": [{ id: "api-auth-better-auth-drizzle-hono", preloaded: false }],
        "api-observability": [{ id: "api-observability-axiom-pino-sentry", preloaded: false }],
      },
      "web-researcher": {
        "web-framework": [{ id: "web-framework-vue-composition-api", preloaded: false }],
        "web-meta-framework": [{ id: "web-meta-framework-nuxt", preloaded: false }],
        "web-client-state": [{ id: "web-state-pinia", preloaded: false }],
        "web-testing": [{ id: "web-testing-vitest", preloaded: false }],
      },
      "api-researcher": {
        "api-api": [{ id: "api-framework-hono", preloaded: false }],
        "api-database": [{ id: "api-database-drizzle", preloaded: false }],
        "api-auth": [{ id: "api-auth-better-auth-drizzle-hono", preloaded: false }],
        "api-observability": [{ id: "api-observability-axiom-pino-sentry", preloaded: false }],
      },
      "pattern-scout": {
        "web-framework": [{ id: "web-framework-vue-composition-api", preloaded: false }],
        "web-meta-framework": [{ id: "web-meta-framework-nuxt", preloaded: false }],
        "web-client-state": [{ id: "web-state-pinia", preloaded: false }],
        "web-testing": [{ id: "web-testing-vitest", preloaded: false }],
        "api-api": [{ id: "api-framework-hono", preloaded: false }],
        "api-database": [{ id: "api-database-drizzle", preloaded: false }],
        "api-auth": [{ id: "api-auth-better-auth-drizzle-hono", preloaded: false }],
        "api-observability": [{ id: "api-observability-axiom-pino-sentry", preloaded: false }],
      },
      "web-pattern-critique": {
        "web-framework": [{ id: "web-framework-vue-composition-api", preloaded: false }],
        "web-meta-framework": [{ id: "web-meta-framework-nuxt", preloaded: false }],
        "web-client-state": [{ id: "web-state-pinia", preloaded: false }],
        "web-testing": [{ id: "web-testing-vitest", preloaded: false }],
        "api-api": [{ id: "api-framework-hono", preloaded: false }],
        "api-database": [{ id: "api-database-drizzle", preloaded: false }],
        "api-auth": [{ id: "api-auth-better-auth-drizzle-hono", preloaded: false }],
        "api-observability": [{ id: "api-observability-axiom-pino-sentry", preloaded: false }],
        "shared-meta": [{ id: "shared-meta-reviewing", preloaded: true }],
      },
      "agent-summoner": {
        "web-framework": [{ id: "web-framework-vue-composition-api", preloaded: false }],
        "web-meta-framework": [{ id: "web-meta-framework-nuxt", preloaded: false }],
        "web-client-state": [{ id: "web-state-pinia", preloaded: false }],
        "web-testing": [{ id: "web-testing-vitest", preloaded: false }],
        "api-api": [{ id: "api-framework-hono", preloaded: false }],
        "api-database": [{ id: "api-database-drizzle", preloaded: false }],
        "api-auth": [{ id: "api-auth-better-auth-drizzle-hono", preloaded: false }],
        "api-observability": [{ id: "api-observability-axiom-pino-sentry", preloaded: false }],
        "shared-meta": [{ id: "shared-meta-reviewing", preloaded: false }],
      },
      "skill-summoner": {
        "web-framework": [{ id: "web-framework-vue-composition-api", preloaded: false }],
        "web-meta-framework": [{ id: "web-meta-framework-nuxt", preloaded: false }],
        "web-client-state": [{ id: "web-state-pinia", preloaded: false }],
        "web-testing": [{ id: "web-testing-vitest", preloaded: false }],
        "api-api": [{ id: "api-framework-hono", preloaded: false }],
        "api-database": [{ id: "api-database-drizzle", preloaded: false }],
        "api-auth": [{ id: "api-auth-better-auth-drizzle-hono", preloaded: false }],
        "api-observability": [{ id: "api-observability-axiom-pino-sentry", preloaded: false }],
        "shared-meta": [{ id: "shared-meta-reviewing", preloaded: false }],
      },
      documentor: {
        "web-framework": [{ id: "web-framework-vue-composition-api", preloaded: false }],
        "web-meta-framework": [{ id: "web-meta-framework-nuxt", preloaded: false }],
        "web-client-state": [{ id: "web-state-pinia", preloaded: false }],
        "web-testing": [{ id: "web-testing-vitest", preloaded: false }],
        "api-api": [{ id: "api-framework-hono", preloaded: false }],
        "api-database": [{ id: "api-database-drizzle", preloaded: false }],
        "api-auth": [{ id: "api-auth-better-auth-drizzle-hono", preloaded: false }],
        "api-observability": [{ id: "api-observability-axiom-pino-sentry", preloaded: false }],
        "shared-meta": [{ id: "shared-meta-reviewing", preloaded: false }],
      },
      "web-tester": {
        "web-testing": [
          { id: "web-testing-playwright-e2e", preloaded: false },
          { id: "web-testing-vitest", preloaded: false },
        ],
      },
    },
  },
  {
    id: "remix-stack",
    name: "Remix Full-Stack",
    description: "Remix + form-centric DX",
    philosophy: "Web standards and excellent forms handling",
    agents: {
      "web-developer": {
        "web-framework": [{ id: "web-framework-react", preloaded: true }],
        "web-meta-framework": [{ id: "web-meta-framework-remix", preloaded: true }],
        "web-testing": [{ id: "web-testing-vitest", preloaded: false }],
        "shared-tooling": SHARED_TOOLING,
        "web-tooling": [{ id: "web-tooling-vite", preloaded: false }],
      },
      "api-developer": {
        "api-api": [{ id: "api-framework-hono", preloaded: true }],
        "api-database": [{ id: "api-database-drizzle", preloaded: true }],
        "api-auth": [{ id: "api-auth-better-auth-drizzle-hono", preloaded: false }],
        "api-observability": [{ id: "api-observability-axiom-pino-sentry", preloaded: false }],
        "shared-tooling": SHARED_TOOLING,
      },
      "web-reviewer": {
        "shared-meta": [{ id: "shared-meta-reviewing", preloaded: true }],
        "web-framework": [{ id: "web-framework-react", preloaded: false }],
        "web-meta-framework": [{ id: "web-meta-framework-remix", preloaded: false }],
        "web-testing": [{ id: "web-testing-vitest", preloaded: false }],
      },
      "api-reviewer": {
        "shared-meta": [{ id: "shared-meta-reviewing", preloaded: true }],
        "api-api": [{ id: "api-framework-hono", preloaded: false }],
        "api-database": [{ id: "api-database-drizzle", preloaded: false }],
        "api-auth": [{ id: "api-auth-better-auth-drizzle-hono", preloaded: false }],
        "api-observability": [{ id: "api-observability-axiom-pino-sentry", preloaded: false }],
      },
      "web-pm": {
        "web-framework": [{ id: "web-framework-react", preloaded: false }],
        "web-meta-framework": [{ id: "web-meta-framework-remix", preloaded: false }],
        "web-testing": [{ id: "web-testing-vitest", preloaded: false }],
        "api-api": [{ id: "api-framework-hono", preloaded: false }],
        "api-database": [{ id: "api-database-drizzle", preloaded: false }],
        "api-auth": [{ id: "api-auth-better-auth-drizzle-hono", preloaded: false }],
        "api-observability": [{ id: "api-observability-axiom-pino-sentry", preloaded: false }],
      },
      "web-architecture": {
        "api-api": [{ id: "api-framework-hono", preloaded: false }],
        "api-database": [{ id: "api-database-drizzle", preloaded: false }],
        "api-auth": [{ id: "api-auth-better-auth-drizzle-hono", preloaded: false }],
        "api-observability": [{ id: "api-observability-axiom-pino-sentry", preloaded: false }],
      },
      "web-researcher": {
        "web-framework": [{ id: "web-framework-react", preloaded: false }],
        "web-meta-framework": [{ id: "web-meta-framework-remix", preloaded: false }],
        "web-testing": [{ id: "web-testing-vitest", preloaded: false }],
      },
      "api-researcher": {
        "api-api": [{ id: "api-framework-hono", preloaded: false }],
        "api-database": [{ id: "api-database-drizzle", preloaded: false }],
        "api-auth": [{ id: "api-auth-better-auth-drizzle-hono", preloaded: false }],
        "api-observability": [{ id: "api-observability-axiom-pino-sentry", preloaded: false }],
      },
      "pattern-scout": {
        "web-framework": [{ id: "web-framework-react", preloaded: false }],
        "web-meta-framework": [{ id: "web-meta-framework-remix", preloaded: false }],
        "web-testing": [{ id: "web-testing-vitest", preloaded: false }],
        "api-api": [{ id: "api-framework-hono", preloaded: false }],
        "api-database": [{ id: "api-database-drizzle", preloaded: false }],
        "api-auth": [{ id: "api-auth-better-auth-drizzle-hono", preloaded: false }],
        "api-observability": [{ id: "api-observability-axiom-pino-sentry", preloaded: false }],
      },
      "web-pattern-critique": {
        "web-framework": [{ id: "web-framework-react", preloaded: false }],
        "web-meta-framework": [{ id: "web-meta-framework-remix", preloaded: false }],
        "web-testing": [{ id: "web-testing-vitest", preloaded: false }],
        "api-api": [{ id: "api-framework-hono", preloaded: false }],
        "api-database": [{ id: "api-database-drizzle", preloaded: false }],
        "api-auth": [{ id: "api-auth-better-auth-drizzle-hono", preloaded: false }],
        "api-observability": [{ id: "api-observability-axiom-pino-sentry", preloaded: false }],
        "shared-meta": [{ id: "shared-meta-reviewing", preloaded: true }],
      },
      "agent-summoner": {
        "web-framework": [{ id: "web-framework-react", preloaded: false }],
        "web-meta-framework": [{ id: "web-meta-framework-remix", preloaded: false }],
        "web-testing": [{ id: "web-testing-vitest", preloaded: false }],
        "api-api": [{ id: "api-framework-hono", preloaded: false }],
        "api-database": [{ id: "api-database-drizzle", preloaded: false }],
        "api-auth": [{ id: "api-auth-better-auth-drizzle-hono", preloaded: false }],
        "api-observability": [{ id: "api-observability-axiom-pino-sentry", preloaded: false }],
        "shared-meta": [{ id: "shared-meta-reviewing", preloaded: false }],
      },
      "skill-summoner": {
        "web-framework": [{ id: "web-framework-react", preloaded: false }],
        "web-meta-framework": [{ id: "web-meta-framework-remix", preloaded: false }],
        "web-testing": [{ id: "web-testing-vitest", preloaded: false }],
        "api-api": [{ id: "api-framework-hono", preloaded: false }],
        "api-database": [{ id: "api-database-drizzle", preloaded: false }],
        "api-auth": [{ id: "api-auth-better-auth-drizzle-hono", preloaded: false }],
        "api-observability": [{ id: "api-observability-axiom-pino-sentry", preloaded: false }],
        "shared-meta": [{ id: "shared-meta-reviewing", preloaded: false }],
      },
      documentor: {
        "web-framework": [{ id: "web-framework-react", preloaded: false }],
        "web-meta-framework": [{ id: "web-meta-framework-remix", preloaded: false }],
        "web-testing": [{ id: "web-testing-vitest", preloaded: false }],
        "api-api": [{ id: "api-framework-hono", preloaded: false }],
        "api-database": [{ id: "api-database-drizzle", preloaded: false }],
        "api-auth": [{ id: "api-auth-better-auth-drizzle-hono", preloaded: false }],
        "api-observability": [{ id: "api-observability-axiom-pino-sentry", preloaded: false }],
        "shared-meta": [{ id: "shared-meta-reviewing", preloaded: false }],
      },
      "web-tester": {
        "web-testing": [
          { id: "web-testing-playwright-e2e", preloaded: false },
          { id: "web-testing-vitest", preloaded: false },
        ],
      },
    },
  },
  {
    id: "vue-stack",
    name: "Modern Vue Stack",
    description: "Vue + Pinia + Tailwind",
    philosophy: "Progressive and approachable",
    agents: {
      "web-developer": {
        "web-framework": [{ id: "web-framework-vue-composition-api", preloaded: true }],
        "web-client-state": [{ id: "web-state-pinia", preloaded: false }],
        "web-testing": [{ id: "web-testing-vitest", preloaded: false }],
        "shared-tooling": SHARED_TOOLING,
        "web-tooling": [{ id: "web-tooling-vite", preloaded: false }],
      },
      "api-developer": {
        "api-api": [{ id: "api-framework-hono", preloaded: true }],
        "api-database": [{ id: "api-database-drizzle", preloaded: true }],
        "api-auth": [{ id: "api-auth-better-auth-drizzle-hono", preloaded: false }],
        "api-observability": [{ id: "api-observability-axiom-pino-sentry", preloaded: false }],
        "shared-tooling": SHARED_TOOLING,
      },
      "web-reviewer": {
        "shared-meta": [{ id: "shared-meta-reviewing", preloaded: true }],
        "web-framework": [{ id: "web-framework-vue-composition-api", preloaded: false }],
        "web-client-state": [{ id: "web-state-pinia", preloaded: false }],
        "web-testing": [{ id: "web-testing-vitest", preloaded: false }],
      },
      "api-reviewer": {
        "shared-meta": [{ id: "shared-meta-reviewing", preloaded: true }],
        "api-api": [{ id: "api-framework-hono", preloaded: false }],
        "api-database": [{ id: "api-database-drizzle", preloaded: false }],
        "api-auth": [{ id: "api-auth-better-auth-drizzle-hono", preloaded: false }],
        "api-observability": [{ id: "api-observability-axiom-pino-sentry", preloaded: false }],
      },
      "web-pm": {
        "web-framework": [{ id: "web-framework-vue-composition-api", preloaded: false }],
        "web-client-state": [{ id: "web-state-pinia", preloaded: false }],
        "web-testing": [{ id: "web-testing-vitest", preloaded: false }],
        "api-api": [{ id: "api-framework-hono", preloaded: false }],
        "api-database": [{ id: "api-database-drizzle", preloaded: false }],
        "api-auth": [{ id: "api-auth-better-auth-drizzle-hono", preloaded: false }],
        "api-observability": [{ id: "api-observability-axiom-pino-sentry", preloaded: false }],
      },
      "web-architecture": {
        "api-api": [{ id: "api-framework-hono", preloaded: false }],
        "api-database": [{ id: "api-database-drizzle", preloaded: false }],
        "api-auth": [{ id: "api-auth-better-auth-drizzle-hono", preloaded: false }],
        "api-observability": [{ id: "api-observability-axiom-pino-sentry", preloaded: false }],
      },
      "web-researcher": {
        "web-framework": [{ id: "web-framework-vue-composition-api", preloaded: false }],
        "web-client-state": [{ id: "web-state-pinia", preloaded: false }],
        "web-testing": [{ id: "web-testing-vitest", preloaded: false }],
      },
      "api-researcher": {
        "api-api": [{ id: "api-framework-hono", preloaded: false }],
        "api-database": [{ id: "api-database-drizzle", preloaded: false }],
        "api-auth": [{ id: "api-auth-better-auth-drizzle-hono", preloaded: false }],
        "api-observability": [{ id: "api-observability-axiom-pino-sentry", preloaded: false }],
      },
      "pattern-scout": {
        "web-framework": [{ id: "web-framework-vue-composition-api", preloaded: false }],
        "web-client-state": [{ id: "web-state-pinia", preloaded: false }],
        "web-testing": [{ id: "web-testing-vitest", preloaded: false }],
        "api-api": [{ id: "api-framework-hono", preloaded: false }],
        "api-database": [{ id: "api-database-drizzle", preloaded: false }],
        "api-auth": [{ id: "api-auth-better-auth-drizzle-hono", preloaded: false }],
        "api-observability": [{ id: "api-observability-axiom-pino-sentry", preloaded: false }],
      },
      "web-pattern-critique": {
        "web-framework": [{ id: "web-framework-vue-composition-api", preloaded: false }],
        "web-client-state": [{ id: "web-state-pinia", preloaded: false }],
        "web-testing": [{ id: "web-testing-vitest", preloaded: false }],
        "api-api": [{ id: "api-framework-hono", preloaded: false }],
        "api-database": [{ id: "api-database-drizzle", preloaded: false }],
        "api-auth": [{ id: "api-auth-better-auth-drizzle-hono", preloaded: false }],
        "api-observability": [{ id: "api-observability-axiom-pino-sentry", preloaded: false }],
        "shared-meta": [{ id: "shared-meta-reviewing", preloaded: true }],
      },
      "agent-summoner": {
        "web-framework": [{ id: "web-framework-vue-composition-api", preloaded: false }],
        "web-client-state": [{ id: "web-state-pinia", preloaded: false }],
        "web-testing": [{ id: "web-testing-vitest", preloaded: false }],
        "api-api": [{ id: "api-framework-hono", preloaded: false }],
        "api-database": [{ id: "api-database-drizzle", preloaded: false }],
        "api-auth": [{ id: "api-auth-better-auth-drizzle-hono", preloaded: false }],
        "api-observability": [{ id: "api-observability-axiom-pino-sentry", preloaded: false }],
        "shared-meta": [{ id: "shared-meta-reviewing", preloaded: false }],
      },
      "skill-summoner": {
        "web-framework": [{ id: "web-framework-vue-composition-api", preloaded: false }],
        "web-client-state": [{ id: "web-state-pinia", preloaded: false }],
        "web-testing": [{ id: "web-testing-vitest", preloaded: false }],
        "api-api": [{ id: "api-framework-hono", preloaded: false }],
        "api-database": [{ id: "api-database-drizzle", preloaded: false }],
        "api-auth": [{ id: "api-auth-better-auth-drizzle-hono", preloaded: false }],
        "api-observability": [{ id: "api-observability-axiom-pino-sentry", preloaded: false }],
        "shared-meta": [{ id: "shared-meta-reviewing", preloaded: false }],
      },
      documentor: {
        "web-framework": [{ id: "web-framework-vue-composition-api", preloaded: false }],
        "web-client-state": [{ id: "web-state-pinia", preloaded: false }],
        "web-testing": [{ id: "web-testing-vitest", preloaded: false }],
        "api-api": [{ id: "api-framework-hono", preloaded: false }],
        "api-database": [{ id: "api-database-drizzle", preloaded: false }],
        "api-auth": [{ id: "api-auth-better-auth-drizzle-hono", preloaded: false }],
        "api-observability": [{ id: "api-observability-axiom-pino-sentry", preloaded: false }],
        "shared-meta": [{ id: "shared-meta-reviewing", preloaded: false }],
      },
      "web-tester": {
        "web-testing": [
          { id: "web-testing-playwright-e2e", preloaded: false },
          { id: "web-testing-vitest", preloaded: false },
        ],
      },
    },
  },
  {
    id: "solidjs-stack",
    name: "SolidJS Stack",
    description: "SolidJS + Hono full-stack",
    philosophy: "Maximum performance with minimal overhead",
    agents: {
      "web-developer": {
        "web-framework": [{ id: "web-framework-solidjs", preloaded: true }],
        "web-testing": [{ id: "web-testing-vitest", preloaded: false }],
        "shared-tooling": SHARED_TOOLING,
        "web-tooling": [{ id: "web-tooling-vite", preloaded: false }],
      },
      "api-developer": {
        "api-api": [{ id: "api-framework-hono", preloaded: true }],
        "api-database": [{ id: "api-database-drizzle", preloaded: true }],
        "api-auth": [{ id: "api-auth-better-auth-drizzle-hono", preloaded: false }],
        "api-observability": [{ id: "api-observability-axiom-pino-sentry", preloaded: false }],
        "shared-tooling": SHARED_TOOLING,
      },
      "web-reviewer": {
        "shared-meta": [{ id: "shared-meta-reviewing", preloaded: true }],
        "web-framework": [{ id: "web-framework-solidjs", preloaded: false }],
        "web-testing": [{ id: "web-testing-vitest", preloaded: false }],
      },
      "api-reviewer": {
        "shared-meta": [{ id: "shared-meta-reviewing", preloaded: true }],
        "api-api": [{ id: "api-framework-hono", preloaded: false }],
        "api-database": [{ id: "api-database-drizzle", preloaded: false }],
        "api-auth": [{ id: "api-auth-better-auth-drizzle-hono", preloaded: false }],
        "api-observability": [{ id: "api-observability-axiom-pino-sentry", preloaded: false }],
      },
      "web-pm": {
        "web-framework": [{ id: "web-framework-solidjs", preloaded: false }],
        "web-testing": [{ id: "web-testing-vitest", preloaded: false }],
        "api-api": [{ id: "api-framework-hono", preloaded: false }],
        "api-database": [{ id: "api-database-drizzle", preloaded: false }],
        "api-auth": [{ id: "api-auth-better-auth-drizzle-hono", preloaded: false }],
        "api-observability": [{ id: "api-observability-axiom-pino-sentry", preloaded: false }],
      },
      "web-architecture": {
        "api-api": [{ id: "api-framework-hono", preloaded: false }],
        "api-database": [{ id: "api-database-drizzle", preloaded: false }],
        "api-auth": [{ id: "api-auth-better-auth-drizzle-hono", preloaded: false }],
        "api-observability": [{ id: "api-observability-axiom-pino-sentry", preloaded: false }],
      },
      "web-researcher": {
        "web-framework": [{ id: "web-framework-solidjs", preloaded: false }],
        "web-testing": [{ id: "web-testing-vitest", preloaded: false }],
      },
      "api-researcher": {
        "api-api": [{ id: "api-framework-hono", preloaded: false }],
        "api-database": [{ id: "api-database-drizzle", preloaded: false }],
        "api-auth": [{ id: "api-auth-better-auth-drizzle-hono", preloaded: false }],
        "api-observability": [{ id: "api-observability-axiom-pino-sentry", preloaded: false }],
      },
      "pattern-scout": {
        "web-framework": [{ id: "web-framework-solidjs", preloaded: false }],
        "web-testing": [{ id: "web-testing-vitest", preloaded: false }],
        "api-api": [{ id: "api-framework-hono", preloaded: false }],
        "api-database": [{ id: "api-database-drizzle", preloaded: false }],
        "api-auth": [{ id: "api-auth-better-auth-drizzle-hono", preloaded: false }],
        "api-observability": [{ id: "api-observability-axiom-pino-sentry", preloaded: false }],
      },
      "web-pattern-critique": {
        "web-framework": [{ id: "web-framework-solidjs", preloaded: false }],
        "web-testing": [{ id: "web-testing-vitest", preloaded: false }],
        "api-api": [{ id: "api-framework-hono", preloaded: false }],
        "api-database": [{ id: "api-database-drizzle", preloaded: false }],
        "api-auth": [{ id: "api-auth-better-auth-drizzle-hono", preloaded: false }],
        "api-observability": [{ id: "api-observability-axiom-pino-sentry", preloaded: false }],
        "shared-meta": [{ id: "shared-meta-reviewing", preloaded: true }],
      },
      "agent-summoner": {
        "web-framework": [{ id: "web-framework-solidjs", preloaded: false }],
        "web-testing": [{ id: "web-testing-vitest", preloaded: false }],
        "api-api": [{ id: "api-framework-hono", preloaded: false }],
        "api-database": [{ id: "api-database-drizzle", preloaded: false }],
        "api-auth": [{ id: "api-auth-better-auth-drizzle-hono", preloaded: false }],
        "api-observability": [{ id: "api-observability-axiom-pino-sentry", preloaded: false }],
        "shared-meta": [{ id: "shared-meta-reviewing", preloaded: false }],
      },
      "skill-summoner": {
        "web-framework": [{ id: "web-framework-solidjs", preloaded: false }],
        "web-testing": [{ id: "web-testing-vitest", preloaded: false }],
        "api-api": [{ id: "api-framework-hono", preloaded: false }],
        "api-database": [{ id: "api-database-drizzle", preloaded: false }],
        "api-auth": [{ id: "api-auth-better-auth-drizzle-hono", preloaded: false }],
        "api-observability": [{ id: "api-observability-axiom-pino-sentry", preloaded: false }],
        "shared-meta": [{ id: "shared-meta-reviewing", preloaded: false }],
      },
      documentor: {
        "web-framework": [{ id: "web-framework-solidjs", preloaded: false }],
        "web-testing": [{ id: "web-testing-vitest", preloaded: false }],
        "api-api": [{ id: "api-framework-hono", preloaded: false }],
        "api-database": [{ id: "api-database-drizzle", preloaded: false }],
        "api-auth": [{ id: "api-auth-better-auth-drizzle-hono", preloaded: false }],
        "api-observability": [{ id: "api-observability-axiom-pino-sentry", preloaded: false }],
        "shared-meta": [{ id: "shared-meta-reviewing", preloaded: false }],
      },
      "web-tester": {
        "web-testing": [
          { id: "web-testing-playwright-e2e", preloaded: false },
          { id: "web-testing-vitest", preloaded: false },
        ],
      },
    },
  },
  {
    id: "t3-stack",
    name: "T3 Stack",
    description: "Next.js + tRPC + Prisma + Tailwind",
    philosophy: "End-to-end type safety with great DX",
    agents: {
      "web-developer": {
        "web-framework": [{ id: "web-framework-react", preloaded: true }],
        "web-meta-framework": [{ id: "web-meta-framework-nextjs", preloaded: true }],
        "web-styling": [{ id: "web-styling-tailwind", preloaded: false }],
        "web-server-state": [{ id: "web-data-fetching-trpc", preloaded: true }],
        "web-testing": [{ id: "web-testing-vitest", preloaded: false }],
        "shared-tooling": SHARED_TOOLING,
        "web-tooling": [{ id: "web-tooling-vite", preloaded: false }],
      },
      "api-developer": {
        "api-database": [{ id: "api-database-prisma", preloaded: true }],
        "api-auth": [{ id: "api-auth-nextauth", preloaded: false }],
        "shared-tooling": SHARED_TOOLING,
      },
      "web-reviewer": {
        "shared-meta": [{ id: "shared-meta-reviewing", preloaded: true }],
        "web-framework": [{ id: "web-framework-react", preloaded: false }],
        "web-meta-framework": [{ id: "web-meta-framework-nextjs", preloaded: false }],
        "web-styling": [{ id: "web-styling-tailwind", preloaded: false }],
        "web-server-state": [{ id: "web-data-fetching-trpc", preloaded: false }],
        "web-testing": [{ id: "web-testing-vitest", preloaded: false }],
      },
      "api-reviewer": {
        "shared-meta": [{ id: "shared-meta-reviewing", preloaded: true }],
        "api-database": [{ id: "api-database-prisma", preloaded: false }],
        "api-auth": [{ id: "api-auth-nextauth", preloaded: false }],
      },
      "web-pm": {
        "web-framework": [{ id: "web-framework-react", preloaded: false }],
        "web-meta-framework": [{ id: "web-meta-framework-nextjs", preloaded: false }],
        "web-styling": [{ id: "web-styling-tailwind", preloaded: false }],
        "web-server-state": [{ id: "web-data-fetching-trpc", preloaded: false }],
        "web-testing": [{ id: "web-testing-vitest", preloaded: false }],
        "api-database": [{ id: "api-database-prisma", preloaded: false }],
        "api-auth": [{ id: "api-auth-nextauth", preloaded: false }],
      },
      "web-architecture": {
        "api-database": [{ id: "api-database-prisma", preloaded: false }],
        "api-auth": [{ id: "api-auth-nextauth", preloaded: false }],
      },
      "web-researcher": {
        "web-framework": [{ id: "web-framework-react", preloaded: false }],
        "web-meta-framework": [{ id: "web-meta-framework-nextjs", preloaded: false }],
        "web-styling": [{ id: "web-styling-tailwind", preloaded: false }],
        "web-server-state": [{ id: "web-data-fetching-trpc", preloaded: false }],
        "web-testing": [{ id: "web-testing-vitest", preloaded: false }],
      },
      "api-researcher": {
        "api-database": [{ id: "api-database-prisma", preloaded: false }],
        "api-auth": [{ id: "api-auth-nextauth", preloaded: false }],
      },
      "pattern-scout": {
        "web-framework": [{ id: "web-framework-react", preloaded: false }],
        "web-meta-framework": [{ id: "web-meta-framework-nextjs", preloaded: false }],
        "web-styling": [{ id: "web-styling-tailwind", preloaded: false }],
        "web-server-state": [{ id: "web-data-fetching-trpc", preloaded: false }],
        "web-testing": [{ id: "web-testing-vitest", preloaded: false }],
        "api-database": [{ id: "api-database-prisma", preloaded: false }],
        "api-auth": [{ id: "api-auth-nextauth", preloaded: false }],
      },
      "web-pattern-critique": {
        "web-framework": [{ id: "web-framework-react", preloaded: false }],
        "web-meta-framework": [{ id: "web-meta-framework-nextjs", preloaded: false }],
        "web-styling": [{ id: "web-styling-tailwind", preloaded: false }],
        "web-server-state": [{ id: "web-data-fetching-trpc", preloaded: false }],
        "web-testing": [{ id: "web-testing-vitest", preloaded: false }],
        "api-database": [{ id: "api-database-prisma", preloaded: false }],
        "api-auth": [{ id: "api-auth-nextauth", preloaded: false }],
        "shared-meta": [{ id: "shared-meta-reviewing", preloaded: true }],
      },
      "agent-summoner": {
        "web-framework": [{ id: "web-framework-react", preloaded: false }],
        "web-meta-framework": [{ id: "web-meta-framework-nextjs", preloaded: false }],
        "web-styling": [{ id: "web-styling-tailwind", preloaded: false }],
        "web-server-state": [{ id: "web-data-fetching-trpc", preloaded: false }],
        "web-testing": [{ id: "web-testing-vitest", preloaded: false }],
        "api-database": [{ id: "api-database-prisma", preloaded: false }],
        "api-auth": [{ id: "api-auth-nextauth", preloaded: false }],
        "shared-meta": [{ id: "shared-meta-reviewing", preloaded: false }],
      },
      "skill-summoner": {
        "web-framework": [{ id: "web-framework-react", preloaded: false }],
        "web-meta-framework": [{ id: "web-meta-framework-nextjs", preloaded: false }],
        "web-styling": [{ id: "web-styling-tailwind", preloaded: false }],
        "web-server-state": [{ id: "web-data-fetching-trpc", preloaded: false }],
        "web-testing": [{ id: "web-testing-vitest", preloaded: false }],
        "api-database": [{ id: "api-database-prisma", preloaded: false }],
        "api-auth": [{ id: "api-auth-nextauth", preloaded: false }],
        "shared-meta": [{ id: "shared-meta-reviewing", preloaded: false }],
      },
      documentor: {
        "web-framework": [{ id: "web-framework-react", preloaded: false }],
        "web-meta-framework": [{ id: "web-meta-framework-nextjs", preloaded: false }],
        "web-styling": [{ id: "web-styling-tailwind", preloaded: false }],
        "web-server-state": [{ id: "web-data-fetching-trpc", preloaded: false }],
        "web-testing": [{ id: "web-testing-vitest", preloaded: false }],
        "api-database": [{ id: "api-database-prisma", preloaded: false }],
        "api-auth": [{ id: "api-auth-nextauth", preloaded: false }],
        "shared-meta": [{ id: "shared-meta-reviewing", preloaded: false }],
      },
      "web-tester": {
        "web-testing": [
          { id: "web-testing-playwright-e2e", preloaded: false },
          { id: "web-testing-vitest", preloaded: false },
        ],
      },
    },
  },
  {
    id: "sveltekit-stack",
    name: "SvelteKit Full-Stack",
    description: "Svelte 5 + SvelteKit",
    philosophy: "Write less, do more with compiler magic",
    agents: {
      "web-developer": {
        "web-framework": [{ id: "web-framework-svelte", preloaded: true }],
        "web-meta-framework": [{ id: "web-meta-framework-sveltekit", preloaded: true }],
        "web-testing": [{ id: "web-testing-vitest", preloaded: false }],
        "shared-tooling": SHARED_TOOLING,
        "web-tooling": [{ id: "web-tooling-vite", preloaded: false }],
      },
      "api-developer": {
        "api-api": [{ id: "api-framework-hono", preloaded: true }],
        "api-database": [{ id: "api-database-drizzle", preloaded: true }],
        "api-auth": [{ id: "api-auth-better-auth-drizzle-hono", preloaded: false }],
        "api-observability": [{ id: "api-observability-axiom-pino-sentry", preloaded: false }],
        "shared-tooling": SHARED_TOOLING,
      },
      "web-reviewer": {
        "shared-meta": [{ id: "shared-meta-reviewing", preloaded: true }],
        "web-framework": [{ id: "web-framework-svelte", preloaded: false }],
        "web-meta-framework": [{ id: "web-meta-framework-sveltekit", preloaded: false }],
        "web-testing": [{ id: "web-testing-vitest", preloaded: false }],
      },
      "api-reviewer": {
        "shared-meta": [{ id: "shared-meta-reviewing", preloaded: true }],
        "api-api": [{ id: "api-framework-hono", preloaded: false }],
        "api-database": [{ id: "api-database-drizzle", preloaded: false }],
        "api-auth": [{ id: "api-auth-better-auth-drizzle-hono", preloaded: false }],
        "api-observability": [{ id: "api-observability-axiom-pino-sentry", preloaded: false }],
      },
      "web-pm": {
        "web-framework": [{ id: "web-framework-svelte", preloaded: false }],
        "web-meta-framework": [{ id: "web-meta-framework-sveltekit", preloaded: false }],
        "web-testing": [{ id: "web-testing-vitest", preloaded: false }],
        "api-api": [{ id: "api-framework-hono", preloaded: false }],
        "api-database": [{ id: "api-database-drizzle", preloaded: false }],
        "api-auth": [{ id: "api-auth-better-auth-drizzle-hono", preloaded: false }],
        "api-observability": [{ id: "api-observability-axiom-pino-sentry", preloaded: false }],
      },
      "web-architecture": {
        "api-api": [{ id: "api-framework-hono", preloaded: false }],
        "api-database": [{ id: "api-database-drizzle", preloaded: false }],
        "api-auth": [{ id: "api-auth-better-auth-drizzle-hono", preloaded: false }],
        "api-observability": [{ id: "api-observability-axiom-pino-sentry", preloaded: false }],
      },
      "web-researcher": {
        "web-framework": [{ id: "web-framework-svelte", preloaded: false }],
        "web-meta-framework": [{ id: "web-meta-framework-sveltekit", preloaded: false }],
        "web-testing": [{ id: "web-testing-vitest", preloaded: false }],
      },
      "api-researcher": {
        "api-api": [{ id: "api-framework-hono", preloaded: false }],
        "api-database": [{ id: "api-database-drizzle", preloaded: false }],
        "api-auth": [{ id: "api-auth-better-auth-drizzle-hono", preloaded: false }],
        "api-observability": [{ id: "api-observability-axiom-pino-sentry", preloaded: false }],
      },
      "pattern-scout": {
        "web-framework": [{ id: "web-framework-svelte", preloaded: false }],
        "web-meta-framework": [{ id: "web-meta-framework-sveltekit", preloaded: false }],
        "web-testing": [{ id: "web-testing-vitest", preloaded: false }],
        "api-api": [{ id: "api-framework-hono", preloaded: false }],
        "api-database": [{ id: "api-database-drizzle", preloaded: false }],
        "api-auth": [{ id: "api-auth-better-auth-drizzle-hono", preloaded: false }],
        "api-observability": [{ id: "api-observability-axiom-pino-sentry", preloaded: false }],
      },
      "web-pattern-critique": {
        "web-framework": [{ id: "web-framework-svelte", preloaded: false }],
        "web-meta-framework": [{ id: "web-meta-framework-sveltekit", preloaded: false }],
        "web-testing": [{ id: "web-testing-vitest", preloaded: false }],
        "api-api": [{ id: "api-framework-hono", preloaded: false }],
        "api-database": [{ id: "api-database-drizzle", preloaded: false }],
        "api-auth": [{ id: "api-auth-better-auth-drizzle-hono", preloaded: false }],
        "api-observability": [{ id: "api-observability-axiom-pino-sentry", preloaded: false }],
        "shared-meta": [{ id: "shared-meta-reviewing", preloaded: true }],
      },
      "agent-summoner": {
        "web-framework": [{ id: "web-framework-svelte", preloaded: false }],
        "web-meta-framework": [{ id: "web-meta-framework-sveltekit", preloaded: false }],
        "web-testing": [{ id: "web-testing-vitest", preloaded: false }],
        "api-api": [{ id: "api-framework-hono", preloaded: false }],
        "api-database": [{ id: "api-database-drizzle", preloaded: false }],
        "api-auth": [{ id: "api-auth-better-auth-drizzle-hono", preloaded: false }],
        "api-observability": [{ id: "api-observability-axiom-pino-sentry", preloaded: false }],
        "shared-meta": [{ id: "shared-meta-reviewing", preloaded: false }],
      },
      "skill-summoner": {
        "web-framework": [{ id: "web-framework-svelte", preloaded: false }],
        "web-meta-framework": [{ id: "web-meta-framework-sveltekit", preloaded: false }],
        "web-testing": [{ id: "web-testing-vitest", preloaded: false }],
        "api-api": [{ id: "api-framework-hono", preloaded: false }],
        "api-database": [{ id: "api-database-drizzle", preloaded: false }],
        "api-auth": [{ id: "api-auth-better-auth-drizzle-hono", preloaded: false }],
        "api-observability": [{ id: "api-observability-axiom-pino-sentry", preloaded: false }],
        "shared-meta": [{ id: "shared-meta-reviewing", preloaded: false }],
      },
      documentor: {
        "web-framework": [{ id: "web-framework-svelte", preloaded: false }],
        "web-meta-framework": [{ id: "web-meta-framework-sveltekit", preloaded: false }],
        "web-testing": [{ id: "web-testing-vitest", preloaded: false }],
        "api-api": [{ id: "api-framework-hono", preloaded: false }],
        "api-database": [{ id: "api-database-drizzle", preloaded: false }],
        "api-auth": [{ id: "api-auth-better-auth-drizzle-hono", preloaded: false }],
        "api-observability": [{ id: "api-observability-axiom-pino-sentry", preloaded: false }],
        "shared-meta": [{ id: "shared-meta-reviewing", preloaded: false }],
      },
      "web-tester": {
        "web-testing": [
          { id: "web-testing-playwright-e2e", preloaded: false },
          { id: "web-testing-vitest", preloaded: false },
        ],
      },
    },
  },
  {
    id: "astro-stack",
    name: "Astro Content Stack",
    description: "Astro content-first with islands",
    philosophy: "Ship less JavaScript, faster by default",
    agents: {
      "web-developer": {
        "web-meta-framework": [{ id: "web-meta-framework-astro", preloaded: true }],
        "web-testing": [{ id: "web-testing-vitest", preloaded: false }],
        "shared-tooling": SHARED_TOOLING,
        "web-tooling": [{ id: "web-tooling-vite", preloaded: false }],
      },
      "api-developer": {
        "api-api": [{ id: "api-framework-hono", preloaded: true }],
        "api-database": [{ id: "api-database-drizzle", preloaded: true }],
        "api-observability": [{ id: "api-observability-axiom-pino-sentry", preloaded: false }],
        "shared-tooling": SHARED_TOOLING,
      },
      "web-reviewer": {
        "shared-meta": [{ id: "shared-meta-reviewing", preloaded: true }],
        "web-meta-framework": [{ id: "web-meta-framework-astro", preloaded: false }],
        "web-testing": [{ id: "web-testing-vitest", preloaded: false }],
      },
      "api-reviewer": {
        "shared-meta": [{ id: "shared-meta-reviewing", preloaded: true }],
        "api-api": [{ id: "api-framework-hono", preloaded: false }],
        "api-database": [{ id: "api-database-drizzle", preloaded: false }],
        "api-observability": [{ id: "api-observability-axiom-pino-sentry", preloaded: false }],
      },
      "web-pm": {
        "web-meta-framework": [{ id: "web-meta-framework-astro", preloaded: false }],
        "web-testing": [{ id: "web-testing-vitest", preloaded: false }],
        "api-api": [{ id: "api-framework-hono", preloaded: false }],
        "api-database": [{ id: "api-database-drizzle", preloaded: false }],
        "api-observability": [{ id: "api-observability-axiom-pino-sentry", preloaded: false }],
      },
      "web-architecture": {
        "api-api": [{ id: "api-framework-hono", preloaded: false }],
        "api-database": [{ id: "api-database-drizzle", preloaded: false }],
        "api-observability": [{ id: "api-observability-axiom-pino-sentry", preloaded: false }],
      },
      "web-researcher": {
        "web-meta-framework": [{ id: "web-meta-framework-astro", preloaded: false }],
        "web-testing": [{ id: "web-testing-vitest", preloaded: false }],
      },
      "api-researcher": {
        "api-api": [{ id: "api-framework-hono", preloaded: false }],
        "api-database": [{ id: "api-database-drizzle", preloaded: false }],
        "api-observability": [{ id: "api-observability-axiom-pino-sentry", preloaded: false }],
      },
      "pattern-scout": {
        "web-meta-framework": [{ id: "web-meta-framework-astro", preloaded: false }],
        "web-testing": [{ id: "web-testing-vitest", preloaded: false }],
        "api-api": [{ id: "api-framework-hono", preloaded: false }],
        "api-database": [{ id: "api-database-drizzle", preloaded: false }],
        "api-observability": [{ id: "api-observability-axiom-pino-sentry", preloaded: false }],
      },
      "web-pattern-critique": {
        "web-meta-framework": [{ id: "web-meta-framework-astro", preloaded: false }],
        "web-testing": [{ id: "web-testing-vitest", preloaded: false }],
        "api-api": [{ id: "api-framework-hono", preloaded: false }],
        "api-database": [{ id: "api-database-drizzle", preloaded: false }],
        "api-observability": [{ id: "api-observability-axiom-pino-sentry", preloaded: false }],
        "shared-meta": [{ id: "shared-meta-reviewing", preloaded: true }],
      },
      "agent-summoner": {
        "web-meta-framework": [{ id: "web-meta-framework-astro", preloaded: false }],
        "web-testing": [{ id: "web-testing-vitest", preloaded: false }],
        "api-api": [{ id: "api-framework-hono", preloaded: false }],
        "api-database": [{ id: "api-database-drizzle", preloaded: false }],
        "api-observability": [{ id: "api-observability-axiom-pino-sentry", preloaded: false }],
        "shared-meta": [{ id: "shared-meta-reviewing", preloaded: false }],
      },
      "skill-summoner": {
        "web-meta-framework": [{ id: "web-meta-framework-astro", preloaded: false }],
        "web-testing": [{ id: "web-testing-vitest", preloaded: false }],
        "api-api": [{ id: "api-framework-hono", preloaded: false }],
        "api-database": [{ id: "api-database-drizzle", preloaded: false }],
        "api-observability": [{ id: "api-observability-axiom-pino-sentry", preloaded: false }],
        "shared-meta": [{ id: "shared-meta-reviewing", preloaded: false }],
      },
      documentor: {
        "web-meta-framework": [{ id: "web-meta-framework-astro", preloaded: false }],
        "web-testing": [{ id: "web-testing-vitest", preloaded: false }],
        "api-api": [{ id: "api-framework-hono", preloaded: false }],
        "api-database": [{ id: "api-database-drizzle", preloaded: false }],
        "api-observability": [{ id: "api-observability-axiom-pino-sentry", preloaded: false }],
        "shared-meta": [{ id: "shared-meta-reviewing", preloaded: false }],
      },
      "web-tester": {
        "web-testing": [
          { id: "web-testing-playwright-e2e", preloaded: false },
          { id: "web-testing-vitest", preloaded: false },
        ],
      },
    },
  },
];
