import type { CategoryMap } from "../../types";

/**
 * Built-in category definitions, equivalent to config/skill-categories.ts.
 * Source repos may override or extend these via their own config files.
 */
export const defaultCategories: CategoryMap = {
  "web-framework": {
    id: "web-framework",
    displayName: "Framework",
    description: "UI framework (React, Vue, Angular, SolidJS)",
    domain: "web",
    exclusive: true,
    required: true,
    order: 1,
  },
  "web-meta-framework": {
    id: "web-meta-framework",
    displayName: "Meta-Framework",
    description: "Full-stack meta-framework (Next.js, Remix, Nuxt, SvelteKit)",
    domain: "web",
    exclusive: true,
    required: false,
    order: 2,
  },
  "web-styling": {
    id: "web-styling",
    displayName: "Styling",
    description: "CSS approach (SCSS Modules, Tailwind, CVA)",
    domain: "web",
    exclusive: false,
    required: true,
    order: 3,
  },
  "web-client-state": {
    id: "web-client-state",
    displayName: "Client State Management",
    description: "UI state, forms, local data (Zustand, Redux, MobX)",
    domain: "web",
    exclusive: true,
    required: false,
    order: 4,
  },
  "web-server-state": {
    id: "web-server-state",
    displayName: "Server State / Data Fetching",
    description: "API data caching (React Query, SWR)",
    domain: "web",
    exclusive: true,
    required: false,
    order: 5,
  },
  "web-forms": {
    id: "web-forms",
    displayName: "Forms & Validation",
    description: "Form handling and schema validation",
    domain: "web",
    exclusive: false,
    required: false,
    order: 6,
  },
  "web-testing": {
    id: "web-testing",
    displayName: "Testing",
    description: "Unit, integration, and E2E testing",
    domain: "web",
    exclusive: false,
    required: false,
    order: 7,
  },
  "web-ui-components": {
    id: "web-ui-components",
    displayName: "UI Component Library",
    description: "Pre-built component systems (Radix, shadcn)",
    domain: "web",
    exclusive: false,
    required: false,
    order: 8,
  },
  "web-tooling": {
    id: "web-tooling",
    displayName: "Build Tools",
    description: "Frontend build tools and bundlers (Vite, Webpack)",
    domain: "web",
    exclusive: false,
    required: false,
    order: 9,
  },
  "web-mocking": {
    id: "web-mocking",
    displayName: "API Mocking",
    description: "Mock Service Worker for development and testing",
    domain: "web",
    exclusive: false,
    required: false,
    order: 10,
  },
  "web-error-handling": {
    id: "web-error-handling",
    displayName: "Error Handling",
    description: "Error boundaries, result types, and error patterns",
    domain: "web",
    exclusive: false,
    required: false,
    order: 11,
  },
  "web-i18n": {
    id: "web-i18n",
    displayName: "Internationalization",
    description: "i18n libraries (next-intl, react-intl, vue-i18n)",
    domain: "web",
    exclusive: true,
    required: false,
    order: 12,
  },
  "web-file-upload": {
    id: "web-file-upload",
    displayName: "File Upload",
    description: "File upload patterns and handling",
    domain: "web",
    exclusive: false,
    required: false,
    order: 13,
  },
  "web-files": {
    id: "web-files",
    displayName: "Files & Images",
    description: "Image handling and file processing",
    domain: "web",
    exclusive: false,
    required: false,
    order: 14,
  },
  "web-utilities": {
    id: "web-utilities",
    displayName: "Utilities",
    description: "Utility libraries (date-fns, native JS patterns)",
    domain: "web",
    exclusive: false,
    required: false,
    order: 15,
  },
  "web-realtime": {
    id: "web-realtime",
    displayName: "Realtime",
    description: "WebSockets, SSE, and real-time communication",
    domain: "web",
    exclusive: true,
    required: false,
    order: 16,
  },
  "web-animation": {
    id: "web-animation",
    displayName: "Animation",
    description: "Animation libraries and CSS animations",
    domain: "web",
    exclusive: false,
    required: false,
    order: 17,
  },
  "web-pwa": {
    id: "web-pwa",
    displayName: "Progressive Web App",
    description: "Service workers, offline-first patterns, and PWA features",
    domain: "web",
    exclusive: false,
    required: false,
    order: 18,
  },
  "web-accessibility": {
    id: "web-accessibility",
    displayName: "Accessibility",
    description: "WCAG compliance, ARIA, and keyboard navigation",
    domain: "web",
    exclusive: false,
    required: false,
    order: 19,
  },
  "web-performance": {
    id: "web-performance",
    displayName: "Web Performance",
    description: "Bundle optimization, render performance, and code splitting",
    domain: "web",
    exclusive: false,
    required: false,
    order: 20,
  },
  "api-api": {
    id: "api-api",
    displayName: "API Framework",
    description: "Backend framework (Hono, Express, Fastify)",
    domain: "api",
    exclusive: true,
    required: true,
    order: 1,
  },
  "api-database": {
    id: "api-database",
    displayName: "Database ORM",
    description: "Database access layer (Drizzle, Prisma)",
    domain: "api",
    exclusive: true,
    required: false,
    order: 2,
  },
  "api-auth": {
    id: "api-auth",
    displayName: "Authentication",
    description: "Auth solution (Better Auth, Auth.js)",
    domain: "api",
    exclusive: true,
    required: false,
    order: 3,
  },
  "api-observability": {
    id: "api-observability",
    displayName: "Observability",
    description: "Logging, monitoring, error tracking",
    domain: "api",
    exclusive: false,
    required: false,
    order: 4,
  },
  "api-analytics": {
    id: "api-analytics",
    displayName: "Analytics",
    description: "Product analytics and tracking",
    domain: "api",
    exclusive: false,
    required: false,
    order: 5,
  },
  "api-email": {
    id: "api-email",
    displayName: "Email",
    description: "Transactional email (Resend, Sendgrid)",
    domain: "api",
    exclusive: true,
    required: false,
    order: 6,
  },
  "api-ai": {
    id: "api-ai",
    displayName: "AI & LLM",
    description: "AI SDKs, LLM integration, and RAG patterns",
    domain: "api",
    exclusive: false,
    required: false,
    order: 7,
  },
  "api-baas": {
    id: "api-baas",
    displayName: "Backend as a Service",
    description: "Managed backend platforms (Supabase, Firebase)",
    domain: "api",
    exclusive: true,
    required: false,
    order: 8,
  },
  "api-performance": {
    id: "api-performance",
    displayName: "Performance",
    description: "API performance patterns and optimization",
    domain: "api",
    exclusive: false,
    required: false,
    order: 9,
  },
  "mobile-framework": {
    id: "mobile-framework",
    displayName: "Mobile Framework",
    description: "Native mobile framework (React Native, Expo)",
    domain: "mobile",
    exclusive: false,
    required: true,
    order: 1,
  },
  "shared-monorepo": {
    id: "shared-monorepo",
    displayName: "Monorepo",
    description: "Monorepo tooling (Turborepo, Nx)",
    domain: "shared",
    exclusive: true,
    required: false,
    order: 1,
  },
  "shared-tooling": {
    id: "shared-tooling",
    displayName: "Build Tooling",
    description: "ESLint, Prettier, TypeScript, Vite",
    domain: "shared",
    exclusive: false,
    required: false,
    order: 2,
  },
  "shared-security": {
    id: "shared-security",
    displayName: "Security",
    description: "Authentication security patterns and best practices",
    domain: "shared",
    exclusive: false,
    required: false,
    order: 3,
  },
  "shared-meta": {
    id: "shared-meta",
    displayName: "Meta",
    description: "Research methodology and code review guidance",
    domain: "shared",
    exclusive: false,
    required: false,
    order: 4,
  },
  "shared-ci-cd": {
    id: "shared-ci-cd",
    displayName: "CI/CD",
    description: "Continuous integration and deployment pipelines",
    domain: "shared",
    exclusive: false,
    required: false,
    order: 7,
  },
  "cli-framework": {
    id: "cli-framework",
    displayName: "CLI Framework",
    description: "CLI application framework (Commander, oclif)",
    domain: "cli",
    exclusive: true,
    required: true,
    order: 1,
  },
};
