import type { AgentName, MergedSkillsMatrix } from "../../types";
import { typedKeys } from "../../utils/typed-object";

const MULTI_LINE_THRESHOLD = 6;

/**
 * Generates a config-types.ts source from marketplace data.
 * The generated file provides type safety for config.ts via `import type` + `satisfies`.
 */
export function generateConfigTypesSource(
  matrix: MergedSkillsMatrix,
  agentNames: AgentName[],
): string {
  const skillIds = typedKeys(matrix.skills).sort();
  const sortedAgents = [...agentNames].sort();

  const domains = extractDomains(matrix);
  const subcategories = typedKeys(matrix.categories).sort();

  return `// AUTO-GENERATED by agentsinc — DO NOT EDIT

export type SkillId = ${formatUnion(skillIds)};

export type AgentName = ${formatUnion(sortedAgents)};

export type Domain = ${formatUnion(domains)};

export type Subcategory = ${formatUnion(subcategories)};

export type InstallMode = "local" | "plugin";

export type SkillAssignment = SkillId | { id: SkillId; preloaded: boolean };

export type StackAgentConfig = Partial<Record<Subcategory, SkillAssignment>>;

export interface ProjectConfig {
  /** Config version @default "1" */
  version?: "1";

  /** Project/plugin name (kebab-case) */
  name: string;

  /** Project description */
  description?: string;

  /** Selected agent names */
  agents: AgentName[];

  /** Selected skill IDs */
  skills: SkillId[];

  /** Author handle (e.g., "@vince") */
  author?: string;

  /** Installation mode: local copies skills, plugin uses native plugins */
  installMode?: InstallMode;

  /** Stack configuration: agent -> subcategory -> skill assignment */
  stack?: Partial<Record<AgentName, StackAgentConfig>>;

  /** Skills source path or URL */
  source?: string;

  /** Marketplace identifier for plugin installation */
  marketplace?: string;

  /** Agents source path or URL (when agents come from a different source than skills) */
  agentsSource?: string;

  /** Selected domains from the wizard */
  domains?: Domain[];

  /** Selected agents from the wizard */
  selectedAgents?: AgentName[];
}
`;
}

function extractDomains(matrix: MergedSkillsMatrix): string[] {
  const domainSet = new Set<string>();
  for (const category of Object.values(matrix.categories)) {
    if (category?.domain) {
      domainSet.add(category.domain);
    }
  }
  return [...domainSet].sort();
}

function formatUnion(members: string[]): string {
  if (members.length === 0) {
    return "string";
  }

  const quoted = members.map((m) => `"${m}"`);

  if (quoted.length < MULTI_LINE_THRESHOLD) {
    return quoted.join(" | ");
  }

  return "\n" + quoted.map((q) => `  | ${q}`).join("\n");
}
