import { describe, it, expect, beforeEach, afterEach, vi } from "vitest";
import path from "path";
import { mkdir, readFile } from "fs/promises";

// Override GLOBAL_INSTALL_ROOT to a non-existent path so getGlobalConfigTypesPath
// returns null. This prevents the dev machine's real ~/.claude-src/ from affecting tests.
vi.mock("../../../consts", async (importOriginal) => {
  const mod = await importOriginal<typeof import("../../../consts")>();
  return { ...mod, GLOBAL_INSTALL_ROOT: "/tmp/nonexistent-global-root" };
});

import {
  generateConfigTypesSource,
  generateProjectConfigTypesSource,
  getGlobalConfigTypesPath,
  loadConfigTypesDataInBackground,
  regenerateConfigTypes,
  type ConfigTypesBackgroundData,
} from "../config-types-writer";
import { createTempDir, cleanupTempDir } from "../../__tests__/test-fs-utils";
import { createMockSkill } from "../../__tests__/factories/skill-factories.js";
import { createMockMatrix } from "../../__tests__/factories/matrix-factories.js";
import { createMockCategory } from "../../__tests__/factories/category-factories.js";
import { buildProjectConfig, buildAgentConfigs } from "../../__tests__/factories/config-factories.js";
import { SKILLS, TEST_CATEGORIES } from "../../__tests__/test-fixtures";
import {
  EMPTY_MATRIX,
  FULLSTACK_PAIR_MATRIX,
  SINGLE_REACT_MATRIX,
  SCSS_HONO_REACT_MATRIX,
  HONO_REACT_MATRIX,
} from "../../__tests__/mock-data/mock-matrices";
import { CLAUDE_SRC_DIR, CLI_BIN_NAME, STANDARD_FILES } from "../../../consts";

import type {
  AgentName,
  CategoryDefinition,
  CategoryPath,
  SkillId,
  Category,
} from "../../../types";

function makeBackgroundData(
  skills: Record<string, ReturnType<typeof createMockSkill>>,
  agentNames: AgentName[] = [],
  customAgentNames: AgentName[] = [],
): Promise<ConfigTypesBackgroundData> {
  return Promise.resolve({
    matrix: createMockMatrix(skills),
    agentNames,
    customAgentNames,
  });
}

describe("generateConfigTypesSource", () => {
  it("includes auto-generated header comment", () => {
    const matrix = EMPTY_MATRIX;
    const source = generateConfigTypesSource(matrix, []);
    expect(source).toContain("// AUTO-GENERATED by agentsinc — DO NOT EDIT");
  });

  it("generates SkillId union from matrix skills", () => {
    const matrix = FULLSTACK_PAIR_MATRIX;
    const source = generateConfigTypesSource(matrix, []);
    expect(source).toContain('"api-framework-hono"');
    expect(source).toContain('"web-framework-react"');
    expect(source).toContain("export type SkillId =");
  });

  it("generates AgentName union from provided agent names", () => {
    const matrix = EMPTY_MATRIX;
    const agentNames: AgentName[] = ["web-developer", "api-developer"];
    const source = generateConfigTypesSource(matrix, agentNames);
    expect(source).toContain('"api-developer"');
    expect(source).toContain('"web-developer"');
    expect(source).toContain("export type AgentName =");
  });

  it("sorts union members alphabetically", () => {
    const matrix = SCSS_HONO_REACT_MATRIX;
    const agentNames: AgentName[] = ["web-developer", "api-developer", "cli-developer"];
    const source = generateConfigTypesSource(matrix, agentNames);

    // Verify skill IDs are sorted (api before web)
    const skillIdLine = source.split("\n").find((l) => l.startsWith("export type SkillId"));
    expect(skillIdLine).toContain("export type SkillId");
    const apiIdx = source.indexOf('"api-framework-hono"');
    const webFrameworkIdx = source.indexOf('"web-framework-react"');
    const webStylingIdx = source.indexOf('"web-styling-scss-modules"');
    expect(apiIdx).toBeLessThan(webFrameworkIdx);
    expect(webFrameworkIdx).toBeLessThan(webStylingIdx);

    // Verify agent names are sorted
    const apiDevIdx = source.indexOf('"api-developer"');
    const cliDevIdx = source.indexOf('"cli-developer"');
    const webDevIdx = source.indexOf('"web-developer"');
    expect(apiDevIdx).toBeLessThan(cliDevIdx);
    expect(cliDevIdx).toBeLessThan(webDevIdx);
  });

  it("generates Domain type from matrix categories", () => {
    const categories = {
      "web-framework": TEST_CATEGORIES.framework,
      "api-api": { ...TEST_CATEGORIES.api, displayName: "API", domain: "api" },
    } as Record<Category, CategoryDefinition>;

    const matrix = createMockMatrix({}, { categories });
    const source = generateConfigTypesSource(matrix, []);
    expect(source).toContain('export type Domain = "api" | "web";');
  });

  it("generates Category union from matrix category keys", () => {
    const categories = {
      "web-framework": TEST_CATEGORIES.framework,
      "api-api": { ...TEST_CATEGORIES.api, displayName: "API", domain: "api" },
      "web-styling": TEST_CATEGORIES.styling,
    } as Record<Category, CategoryDefinition>;

    const matrix = createMockMatrix({}, { categories });
    const source = generateConfigTypesSource(matrix, []);
    expect(source).toContain('export type Category = "api-api" | "web-framework" | "web-styling";');
  });

  it("falls back to string for empty categories", () => {
    const matrix = createMockMatrix({}, { categories: {} as Record<Category, CategoryDefinition> });
    const source = generateConfigTypesSource(matrix, []);
    expect(source).toContain("export type Category = string;");
  });

  it("generates InstallMode type", () => {
    const matrix = EMPTY_MATRIX;
    const source = generateConfigTypesSource(matrix, []);
    expect(source).toContain('export type InstallMode = "eject" | "plugin" | "mixed";');
  });

  it("generates generic SkillAssignment type with default type parameter", () => {
    const matrix = EMPTY_MATRIX;
    const source = generateConfigTypesSource(matrix, []);
    expect(source).toContain(
      "export type SkillAssignment<S extends SkillId = SkillId> = S | { id: S; preloaded: boolean };",
    );
  });

  it("falls back to loose StackAgentConfig when no categories have skills", () => {
    const matrix = EMPTY_MATRIX;
    const source = generateConfigTypesSource(matrix, []);
    expect(source).toContain(
      "export type StackAgentConfig = Partial<Record<Category, SkillAssignment[]>>;",
    );
  });

  it("generates per-category constrained StackAgentConfig with single skill", () => {
    const categories = {
      "web-framework": TEST_CATEGORIES.framework,
    } as Record<Category, CategoryDefinition>;
    const matrix = createMockMatrix(SKILLS.react, { categories });
    const source = generateConfigTypesSource(matrix, []);
    expect(source).toContain("export type StackAgentConfig = {");
    expect(source).toContain('  "web-framework"?: SkillAssignment<"web-framework-react">[];');
    expect(source).toContain("};");
  });

  it("generates per-category constrained StackAgentConfig with multiple categories", () => {
    const categories = {
      "web-framework": TEST_CATEGORIES.framework,
      "web-styling": TEST_CATEGORIES.styling,
      "api-api": { ...TEST_CATEGORIES.api, displayName: "API", domain: "api" },
    } as Record<Category, CategoryDefinition>;
    const matrix = createMockMatrix(SKILLS.react, SKILLS.scss, SKILLS.hono, { categories });
    const source = generateConfigTypesSource(matrix, []);
    expect(source).toContain("export type StackAgentConfig = {");
    expect(source).toContain('  "api-api"?: SkillAssignment<"api-framework-hono">[];');
    expect(source).toContain('  "web-framework"?: SkillAssignment<"web-framework-react">[];');
    expect(source).toContain('  "web-styling"?: SkillAssignment<"web-styling-scss-modules">[];');
  });

  it("generates multi-line union for categories with more than 3 skills", () => {
    const categories = {
      "web-framework": TEST_CATEGORIES.framework,
    } as Record<Category, CategoryDefinition>;
    const matrix = createMockMatrix(
      createMockSkill("web-framework-react"),
      createMockSkill("web-framework-vue-composition-api"),
      // Boundary casts: fictional skill IDs for testing multi-line union generation
      createMockSkill("web-framework-original" as SkillId),
      createMockSkill("web-framework-simple" as SkillId),
      { categories },
    );
    const source = generateConfigTypesSource(matrix, []);
    expect(source).toContain('  "web-framework"?: SkillAssignment<');
    expect(source).toContain('    | "web-framework-original"');
    expect(source).toContain('    | "web-framework-react"');
    expect(source).toContain('    | "web-framework-simple"');
    expect(source).toContain('    | "web-framework-vue-composition-api"');
    expect(source).toContain("  >[];");
  });

  it("omits categories that have no matching skills from StackAgentConfig", () => {
    const categories = {
      "web-framework": TEST_CATEGORIES.framework,
      "web-styling": TEST_CATEGORIES.styling,
    } as Record<Category, CategoryDefinition>;
    // Only add a React skill (web-framework), no styling skills
    const matrix = createMockMatrix(SKILLS.react, { categories });
    const source = generateConfigTypesSource(matrix, []);
    expect(source).toContain("export type StackAgentConfig = {");
    expect(source).toContain('"web-framework"?:');
    expect(source).not.toContain('"web-styling"?:');
  });

  it("generates ProjectConfig interface with ProjectAgentName stack keys", () => {
    const matrix = EMPTY_MATRIX;
    const source = generateConfigTypesSource(matrix, []);
    expect(source).toContain("export interface ProjectConfig {");
    expect(source).toContain("name: string;");
    expect(source).toContain("agents: AgentScopeConfig[];");
    expect(source).toContain("skills: SkillConfig[];");
    expect(source).toContain("stack?: Partial<Record<ProjectAgentName, StackAgentConfig>>;");
    expect(source).toContain("domains?: Domain[];");
    expect(source).toContain("selectedAgents?: SelectedAgentName[];");
    expect(source).toContain("source?: string;");
    expect(source).toContain("marketplace?: string;");
    expect(source).toContain("agentsSource?: string;");
    expect(source).toContain("author?: string;");
    expect(source).toContain("description?: string;");
  });

  it("generates SelectedAgentName = AgentName for standalone config without config param", () => {
    const matrix = EMPTY_MATRIX;
    const source = generateConfigTypesSource(matrix, []);
    expect(source).toContain("export type SelectedAgentName = AgentName;");
  });

  it("generates ProjectAgentName = SelectedAgentName for global config", () => {
    const matrix = createMockMatrix(SKILLS.react);
    const agentNames: AgentName[] = ["web-developer", "web-reviewer"];
    const config = buildProjectConfig({
      agents: buildAgentConfigs(["web-developer", "web-reviewer"], { scope: "global" }),
      selectedAgents: ["web-developer", "web-reviewer"],
    });
    const source = generateConfigTypesSource(matrix, agentNames, [], undefined, config);
    expect(source).toContain("export type ProjectAgentName = SelectedAgentName;");
  });

  it("generates ProjectAgentName narrowed to project-scoped agents", () => {
    const matrix = createMockMatrix(SKILLS.react);
    const agentNames: AgentName[] = ["web-developer", "web-reviewer", "api-developer"];
    const config = buildProjectConfig({
      agents: [
        ...buildAgentConfigs(["web-developer"], { scope: "global" }),
        ...buildAgentConfigs(["web-reviewer", "api-developer"], { scope: "project" }),
      ],
      selectedAgents: ["web-developer", "web-reviewer", "api-developer"],
    });
    const source = generateConfigTypesSource(matrix, agentNames, [], undefined, config);
    expect(source).toContain('export type ProjectAgentName = "web-reviewer" | "api-developer"');
    expect(source).not.toContain("export type ProjectAgentName = SelectedAgentName");
  });

  it("falls back to string for empty skills", () => {
    const matrix = EMPTY_MATRIX;
    const source = generateConfigTypesSource(matrix, []);
    expect(source).toContain("export type SkillId = string;");
  });

  it("falls back to string for empty agents", () => {
    const matrix = SINGLE_REACT_MATRIX;
    const source = generateConfigTypesSource(matrix, []);
    expect(source).toContain("export type AgentName = string;");
  });

  it("falls back to string for empty domains", () => {
    const matrix = createMockMatrix(SKILLS.react, {
      categories: {} as Record<Category, CategoryDefinition>,
    });
    const source = generateConfigTypesSource(matrix, []);
    expect(source).toContain("export type Domain = string;");
  });

  it("uses single-line format for 5 or fewer union members", () => {
    const matrix = HONO_REACT_MATRIX;
    const source = generateConfigTypesSource(matrix, []);
    // 2 skills = single-line union
    expect(source).toContain('export type SkillId = "api-framework-hono" | "web-framework-react";');
  });

  it("uses multi-line format for 6 or more union members", () => {
    const ids = [
      "api-database-drizzle",
      "api-framework-hono",
      "web-framework-react",
      "web-framework-vue-composition-api",
      "web-state-zustand",
      "web-styling-scss-modules",
    ] as const;
    const matrix = createMockMatrix(
      ...ids.map((id) => createMockSkill(id, { category: "web-framework" })),
    );
    const source = generateConfigTypesSource(matrix, []);
    // 6 skills = multi-line union with leading pipes
    expect(source).toContain('  | "api-database-drizzle"');
    expect(source).toContain('  | "web-styling-scss-modules"');
  });

  describe("sectioned unions with custom and marketplace comments", () => {
    it("shows custom skills first with section comments", () => {
      // Boundary cast: custom skill IDs may not match built-in SkillId prefix patterns
      const acmeDeploy = "acme-deploy-pipeline" as SkillId;
      const acmeAudit = "acme-audit-runner" as SkillId;
      const matrix = createMockMatrix(
        createMockSkill(acmeDeploy, { category: "web-framework", custom: true }),
        createMockSkill(acmeAudit, { category: "web-framework", custom: true }),
        SKILLS.react,
        SKILLS.scss,
      );
      const source = generateConfigTypesSource(matrix, []);

      // Custom skills appear first with comment
      expect(source).toContain("// Custom");
      expect(source).toContain("// Marketplace");

      // Verify ordering: custom before marketplace
      const customIdx = source.indexOf("// Custom");
      const marketplaceIdx = source.indexOf("// Marketplace");
      expect(customIdx).toBeLessThan(marketplaceIdx);

      // Verify custom skills are in the custom section
      const acmeDeployIdx = source.indexOf('"acme-deploy-pipeline"');
      const acmeAuditIdx = source.indexOf('"acme-audit-runner"');
      expect(acmeAuditIdx).toBeGreaterThan(customIdx);
      expect(acmeAuditIdx).toBeLessThan(marketplaceIdx);
      expect(acmeDeployIdx).toBeGreaterThan(customIdx);
      expect(acmeDeployIdx).toBeLessThan(marketplaceIdx);

      // Marketplace skills appear after the marketplace comment
      const reactIdx = source.indexOf('"web-framework-react"');
      const scssIdx = source.indexOf('"web-styling-scss-modules"');
      expect(reactIdx).toBeGreaterThan(marketplaceIdx);
      expect(scssIdx).toBeGreaterThan(marketplaceIdx);
    });

    it("treats extra skill IDs as custom", () => {
      const matrix = SINGLE_REACT_MATRIX;
      // Boundary cast: extra skill ID may not match built-in SkillId prefix patterns
      const source = generateConfigTypesSource(matrix, [], [], {
        extraSkillIds: ["acme-deploy-pipeline" as string],
      });
      expect(source).toContain("// Custom");
      expect(source).toContain("// Marketplace");

      const customIdx = source.indexOf("// Custom");
      const extraIdx = source.indexOf('"acme-deploy-pipeline"');
      expect(extraIdx).toBeGreaterThan(customIdx);
    });

    it("omits comments when no custom skills exist", () => {
      const matrix = FULLSTACK_PAIR_MATRIX;
      const source = generateConfigTypesSource(matrix, []);
      expect(source).not.toContain("// Custom");
      expect(source).not.toContain("// Marketplace");
    });

    it("shows only Custom header when all skills are custom", () => {
      // Boundary cast: custom skill IDs may not match built-in SkillId prefix patterns
      const acmeDeploy = "acme-deploy-pipeline" as SkillId;
      const acmeAudit = "acme-audit-runner" as SkillId;
      const matrix = createMockMatrix(
        createMockSkill(acmeDeploy, { category: "web-framework", custom: true }),
        createMockSkill(acmeAudit, { category: "web-framework", custom: true }),
      );
      const source = generateConfigTypesSource(matrix, []);
      expect(source).toContain("// Custom");
      expect(source).not.toContain("// Marketplace");
    });

    it("shows section comments for custom agent names", () => {
      const matrix = EMPTY_MATRIX;
      const agentNames: AgentName[] = ["api-developer", "web-developer"];
      // Boundary cast: custom agent name not in built-in AgentName union
      const customAgentNames = ["acme-deployer"] as unknown as AgentName[];
      const source = generateConfigTypesSource(
        matrix,
        [...agentNames, ...customAgentNames],
        customAgentNames,
      );
      expect(source).toContain("// Custom");
      expect(source).toContain("// Marketplace");

      const customIdx = source.indexOf("// Custom");
      const marketplaceIdx = source.indexOf("// Marketplace");
      const acmeIdx = source.indexOf('"acme-deployer"');
      expect(acmeIdx).toBeGreaterThan(customIdx);
      expect(acmeIdx).toBeLessThan(marketplaceIdx);
    });

    it("treats extra agent names as custom", () => {
      const matrix = EMPTY_MATRIX;
      const agentNames: AgentName[] = ["web-developer"];
      // Boundary cast: extra agent name may not match built-in AgentName union
      const source = generateConfigTypesSource(matrix, agentNames, [], {
        extraAgentNames: ["custom-agent" as string],
      });
      expect(source).toContain("// Custom");
      expect(source).toContain("// Marketplace");

      const customIdx = source.indexOf("// Custom");
      const customAgentIdx = source.indexOf('"custom-agent"');
      expect(customAgentIdx).toBeGreaterThan(customIdx);
    });

    it("shows section comments for custom categories (derived from custom skills)", () => {
      // Boundary cast: custom skill/category IDs may not match built-in prefix patterns
      const acmeDeploy = "acme-deploy-pipeline" as SkillId;
      const categories = {
        "web-framework": TEST_CATEGORIES.framework,
        "acme-deploy": createMockCategory("acme-deploy" as Category, "Deploy", {
          domain: "web",
        }),
      } as unknown as Record<Category, CategoryDefinition>;

      const matrix = createMockMatrix(
        createMockSkill(acmeDeploy, {
          category: "acme-deploy" as CategoryPath,
          custom: true,
        }),
        { categories },
      );
      const source = generateConfigTypesSource(matrix, []);

      const categoryStart = source.indexOf("export type Category =");
      const categoryEnd = source.indexOf(";", categoryStart);
      const categorySection = source.slice(categoryStart, categoryEnd);

      expect(categorySection).toContain("// Custom");
      expect(categorySection).toContain("// Marketplace");
      expect(categorySection).toContain('"acme-deploy"');
      expect(categorySection).toContain('"web-framework"');
    });

    it("shows section comments for custom domains (derived from custom skills)", () => {
      // Boundary cast: custom skill/category/domain not in built-in unions
      const acmeCi = "acme-ci-runner" as SkillId;
      const categories = {
        "web-framework": TEST_CATEGORIES.framework,
        "devops-ci": createMockCategory("devops-ci" as Category, "CI/CD", {
          domain: "devops" as "web",
        }),
      } as unknown as Record<Category, CategoryDefinition>;

      const matrix = createMockMatrix(
        createMockSkill(acmeCi, {
          category: "devops-ci" as CategoryPath,
          custom: true,
        }),
        { categories },
      );
      const source = generateConfigTypesSource(matrix, []);

      const domainStart = source.indexOf("export type Domain =");
      const domainEnd = source.indexOf(";", domainStart);
      const domainSection = source.slice(domainStart, domainEnd);

      expect(domainSection).toContain("// Custom");
      expect(domainSection).toContain("// Marketplace");
      expect(domainSection).toContain('"devops"');
      expect(domainSection).toContain('"web"');
    });

    it("does not mark domain as custom if it appears on both custom and non-custom categories", () => {
      // Boundary cast: custom skill/category key not in built-in unions
      const acmeTool = "acme-web-tool" as SkillId;
      const categories = {
        "web-framework": TEST_CATEGORIES.framework,
        "web-custom-tool": createMockCategory("web-custom-tool" as Category, "Custom Tool", {
          domain: "web",
        }),
      } as unknown as Record<Category, CategoryDefinition>;

      const matrix = createMockMatrix(
        createMockSkill(acmeTool, {
          category: "web-custom-tool" as CategoryPath,
          custom: true,
        }),
        { categories },
      );
      const source = generateConfigTypesSource(matrix, []);

      // "web" domain appears on both custom and non-custom categories, so no section comments
      const domainStart = source.indexOf("export type Domain =");
      const domainEnd = source.indexOf(";", domainStart);
      const domainSection = source.slice(domainStart, domainEnd);

      expect(domainSection).not.toContain("// Custom");
      expect(domainSection).not.toContain("// Marketplace");
    });

    it("uses multi-line format when section comments are present even with few members", () => {
      // Boundary cast: custom skill ID may not match built-in SkillId prefix patterns
      const acmeDeploy = "acme-deploy-pipeline" as SkillId;
      const matrix = createMockMatrix(
        createMockSkill(acmeDeploy, { category: "web-framework", custom: true }),
        SKILLS.react,
      );
      const source = generateConfigTypesSource(matrix, []);

      // Even with just 2 members, section comments force multi-line format
      expect(source).toContain('  | "acme-deploy-pipeline"');
      expect(source).toContain('  | "web-framework-react"');
    });
  });
});

describe("regenerateConfigTypes", () => {
  let tempDir: string;

  beforeEach(async () => {
    tempDir = await createTempDir("cc-regen-types-test-");
  });

  afterEach(async () => {
    await cleanupTempDir(tempDir);
  });

  it("writes config-types.ts when .claude-src/ exists", async () => {
    const claudeSrcDir = path.join(tempDir, CLAUDE_SRC_DIR);
    await mkdir(claudeSrcDir, { recursive: true });

    const data = makeBackgroundData({
      "web-framework-react": SKILLS.react,
    });

    await regenerateConfigTypes(tempDir, data);

    const configTypesPath = path.join(claudeSrcDir, STANDARD_FILES.CONFIG_TYPES_TS);
    const content = await readFile(configTypesPath, "utf-8");
    expect(content).toContain("// AUTO-GENERATED by agentsinc");
    expect(content).toContain('"web-framework-react"');
  });

  it("creates .claude-src/ and writes config-types.ts when data is provided", async () => {
    // When background data is non-null, writeFile creates directories as needed
    const data = makeBackgroundData({
      "web-framework-react": SKILLS.react,
    });

    await regenerateConfigTypes(tempDir, data);

    const configTypesPath = path.join(tempDir, CLAUDE_SRC_DIR, STANDARD_FILES.CONFIG_TYPES_TS);
    const content = await readFile(configTypesPath, "utf-8");
    expect(content).toContain('"web-framework-react"');
  });

  it("throws when .claude-src/ does not exist", async () => {
    const data = loadConfigTypesDataInBackground(undefined, tempDir);

    await expect(regenerateConfigTypes(tempDir, data)).rejects.toThrow(
      `${CLAUDE_SRC_DIR}/ not found — run '${CLI_BIN_NAME} init' first`,
    );
  });

  it("includes extra skill IDs in the generated output", async () => {
    const claudeSrcDir = path.join(tempDir, CLAUDE_SRC_DIR);
    await mkdir(claudeSrcDir, { recursive: true });

    const data = makeBackgroundData({
      "web-framework-react": SKILLS.react,
    });

    await regenerateConfigTypes(tempDir, data, {
      extraSkillIds: ["acme-deploy-pipeline"],
    });

    const configTypesPath = path.join(claudeSrcDir, STANDARD_FILES.CONFIG_TYPES_TS);
    const content = await readFile(configTypesPath, "utf-8");
    expect(content).toContain('"acme-deploy-pipeline"');
    expect(content).toContain('"web-framework-react"');
  });

  it("does not duplicate extra skill IDs already in the matrix", async () => {
    const claudeSrcDir = path.join(tempDir, CLAUDE_SRC_DIR);
    await mkdir(claudeSrcDir, { recursive: true });

    const data = makeBackgroundData({
      "web-framework-react": SKILLS.react,
    });

    await regenerateConfigTypes(tempDir, data, {
      extraSkillIds: ["web-framework-react"],
    });

    const configTypesPath = path.join(claudeSrcDir, STANDARD_FILES.CONFIG_TYPES_TS);
    const content = await readFile(configTypesPath, "utf-8");
    const matches = content.match(/"web-framework-react"/g);
    // Should appear in SkillId union only once (plus possibly in other type references)
    expect(matches).not.toBeNull();
    expect(matches!.length).toBeGreaterThanOrEqual(1);
  });

  it("includes extra agent names in the generated output", async () => {
    const claudeSrcDir = path.join(tempDir, CLAUDE_SRC_DIR);
    await mkdir(claudeSrcDir, { recursive: true });

    const data = makeBackgroundData({}, ["web-developer"]);

    await regenerateConfigTypes(tempDir, data, {
      extraAgentNames: ["custom-agent"],
    });

    const configTypesPath = path.join(claudeSrcDir, STANDARD_FILES.CONFIG_TYPES_TS);
    const content = await readFile(configTypesPath, "utf-8");
    expect(content).toContain('"custom-agent"');
    expect(content).toContain('"web-developer"');
  });

  it("does not duplicate extra agent names already in the data", async () => {
    const claudeSrcDir = path.join(tempDir, CLAUDE_SRC_DIR);
    await mkdir(claudeSrcDir, { recursive: true });

    const data = makeBackgroundData({}, ["web-developer"]);

    await regenerateConfigTypes(tempDir, data, {
      extraAgentNames: ["web-developer"],
    });

    const configTypesPath = path.join(claudeSrcDir, STANDARD_FILES.CONFIG_TYPES_TS);
    const content = await readFile(configTypesPath, "utf-8");
    // Count occurrences of "web-developer" in the AgentName union section
    // (may span multiple lines due to section comments)
    const agentSectionStart = content.indexOf("export type AgentName =");
    const agentSectionEnd = content.indexOf(";", agentSectionStart);
    const agentSection = content.slice(agentSectionStart, agentSectionEnd);
    const matches = agentSection.match(/"web-developer"/g);
    expect(matches).toHaveLength(1);
  });

  it("propagates errors when background data promise rejects", async () => {
    const failingData = Promise.reject(new Error("Network error"));
    // Prevent unhandled rejection warning
    failingData.catch(() => {});

    await expect(regenerateConfigTypes(tempDir, failingData)).rejects.toThrow("Network error");
  });
});

describe("generateProjectConfigTypesSource", () => {
  it("generates import statement from global config-types", () => {
    const source = generateProjectConfigTypesSource({
      globalTypesImportPath: "../../.claude-src",
      projectSkillIds: [],
      projectAgentNames: [],
      projectDomains: [],
    });
    expect(source).toContain("// AUTO-GENERATED by agentsinc — DO NOT EDIT");
    expect(source).toContain('from "../../.claude-src/config-types"');
    expect(source).toContain("SkillId as GlobalSkillId");
    expect(source).toContain("AgentName as GlobalAgentName");
    expect(source).toContain("Domain as GlobalDomain");
    expect(source).toContain("Category as GlobalCategory");
  });

  it("extends global types with project-only skill IDs", () => {
    const source = generateProjectConfigTypesSource({
      globalTypesImportPath: "../../.claude-src",
      projectSkillIds: ["acme-deploy-pipeline"],
      projectAgentNames: [],
      projectDomains: [],
    });
    expect(source).toContain('export type SkillId = GlobalSkillId | "acme-deploy-pipeline"');
  });

  it("extends global types with project-only agent names", () => {
    const source = generateProjectConfigTypesSource({
      globalTypesImportPath: "../../.claude-src",
      projectSkillIds: [],
      projectAgentNames: ["custom-reviewer"],
      projectDomains: [],
    });
    expect(source).toContain('export type AgentName = GlobalAgentName | "custom-reviewer"');
  });

  it("extends global types with project-only domains", () => {
    const source = generateProjectConfigTypesSource({
      globalTypesImportPath: "../../.claude-src",
      projectSkillIds: [],
      projectAgentNames: [],
      projectDomains: ["devops"],
    });
    expect(source).toContain('export type Domain = GlobalDomain | "devops"');
  });

  it("uses bare global type when no project members exist", () => {
    const source = generateProjectConfigTypesSource({
      globalTypesImportPath: "../../.claude-src",
      projectSkillIds: [],
      projectAgentNames: [],
      projectDomains: [],
    });
    expect(source).toContain("export type SkillId = GlobalSkillId;");
    expect(source).toContain("export type AgentName = GlobalAgentName;");
    expect(source).toContain("export type Domain = GlobalDomain;");
    expect(source).toContain("export type Category = GlobalCategory;");
  });

  it("generates SelectedAgentName for project config with selectedAgentNames", () => {
    const source = generateProjectConfigTypesSource({
      globalTypesImportPath: "../../.claude-src",
      projectSkillIds: [],
      projectAgentNames: ["custom-reviewer", "project-deployer"],
      projectDomains: [],
      selectedAgentNames: ["custom-reviewer", "project-deployer"],
    });
    expect(source).toContain(
      'export type SelectedAgentName = "custom-reviewer" | "project-deployer";',
    );
  });

  it("generates SelectedAgentName = AgentName for project config without selectedAgentNames", () => {
    const source = generateProjectConfigTypesSource({
      globalTypesImportPath: "../../.claude-src",
      projectSkillIds: [],
      projectAgentNames: [],
      projectDomains: [],
    });
    expect(source).toContain("export type SelectedAgentName = AgentName;");
  });

  it("re-exports GlobalCategory when no project categories exist", () => {
    const source = generateProjectConfigTypesSource({
      globalTypesImportPath: "../../.claude-src",
      projectSkillIds: [],
      projectAgentNames: [],
      projectDomains: [],
    });
    expect(source).toContain("export type Category = GlobalCategory;");
    expect(source).toContain("Category as GlobalCategory");
  });

  it("extends GlobalCategory with project-specific categories", () => {
    const source = generateProjectConfigTypesSource({
      globalTypesImportPath: "../../.claude-src",
      projectSkillIds: [],
      projectAgentNames: [],
      projectDomains: [],
      projectCategories: ["custom-tooling"],
    });
    expect(source).toContain('export type Category = GlobalCategory | "custom-tooling"');
    expect(source).toContain("Category as GlobalCategory");
  });

  it("includes ProjectConfig interface template", () => {
    const source = generateProjectConfigTypesSource({
      globalTypesImportPath: "../../.claude-src",
      projectSkillIds: [],
      projectAgentNames: [],
      projectDomains: [],
    });
    expect(source).toContain("export interface ProjectConfig {");
    expect(source).toContain('export type InstallMode = "eject" | "plugin" | "mixed"');
  });

  it("sorts multiple project members alphabetically", () => {
    const source = generateProjectConfigTypesSource({
      globalTypesImportPath: "../../.claude-src",
      projectSkillIds: ["z-custom-tool", "a-custom-tool"],
      projectAgentNames: [],
      projectDomains: [],
    });
    const aIdx = source.indexOf('"a-custom-tool"');
    const zIdx = source.indexOf('"z-custom-tool"');
    expect(aIdx).toBeLessThan(zIdx);
  });

  it("extends global types when all items are global-scoped (full config passed)", () => {
    // When writeProjectConfigTypes receives the full config instead of just project split,
    // global-scoped items should appear as explicit union extensions
    const source = generateProjectConfigTypesSource({
      globalTypesImportPath: "../../.claude-src",
      projectSkillIds: ["web-framework-react", "web-testing-vitest"],
      projectAgentNames: ["web-developer", "web-reviewer"],
      projectDomains: ["web"],
      projectCategories: ["web-framework", "web-testing"],
    });
    expect(source).toContain(
      'export type SkillId = GlobalSkillId | "web-framework-react" | "web-testing-vitest"',
    );
    expect(source).toContain(
      'export type AgentName = GlobalAgentName | "web-developer" | "web-reviewer"',
    );
    expect(source).toContain('export type Domain = GlobalDomain | "web"');
    expect(source).toContain(
      'export type Category = GlobalCategory | "web-framework" | "web-testing"',
    );
  });

  it("extends global types with mixed-scope items (full config passed)", () => {
    // When the full config includes both global and project-scoped items,
    // all items should appear as explicit union extensions
    const source = generateProjectConfigTypesSource({
      globalTypesImportPath: "../../.claude-src",
      projectSkillIds: ["web-framework-react", "project-custom-skill"],
      projectAgentNames: ["web-developer", "custom-reviewer"],
      projectDomains: ["web"],
      projectCategories: ["web-framework"],
    });
    expect(source).toContain(
      'export type SkillId = GlobalSkillId | "project-custom-skill" | "web-framework-react"',
    );
    expect(source).toContain(
      'export type AgentName = GlobalAgentName | "custom-reviewer" | "web-developer"',
    );
  });
});

describe("regenerateConfigTypes with global install", () => {
  let tempDir: string;
  let globalDir: string;

  beforeEach(async () => {
    tempDir = await createTempDir("cc-regen-project-types-test-");
    // Create a fake global install root that simulates ~/.claude-src/config-types.ts
    globalDir = await createTempDir("cc-regen-global-root-test-");
  });

  afterEach(async () => {
    await cleanupTempDir(tempDir);
    await cleanupTempDir(globalDir);
  });

  it("generates project-import config-types when global exists", async () => {
    // Set up the mock to use our fake global root
    const { CLAUDE_SRC_DIR: claudeSrc, STANDARD_FILES: files } = await import("../../../consts");
    const consts = await import("../../../consts");
    // Dynamically override GLOBAL_INSTALL_ROOT for this test
    Object.defineProperty(consts, "GLOBAL_INSTALL_ROOT", { value: globalDir, writable: true });

    try {
      // Create the global config-types.ts so detection succeeds
      const globalClaudeSrc = path.join(globalDir, claudeSrc);
      await mkdir(globalClaudeSrc, { recursive: true });
      const globalTypesPath = path.join(globalClaudeSrc, files.CONFIG_TYPES_TS);
      const { writeFile } = await import("fs/promises");
      await writeFile(globalTypesPath, "// global types");

      // Create project .claude-src/
      const projectClaudeSrc = path.join(tempDir, claudeSrc);
      await mkdir(projectClaudeSrc, { recursive: true });

      const data = makeBackgroundData({
        "web-framework-react": SKILLS.react,
      });

      await regenerateConfigTypes(tempDir, data);

      const configTypesPath = path.join(projectClaudeSrc, files.CONFIG_TYPES_TS);
      const content = await readFile(configTypesPath, "utf-8");

      // Should have import from global, not standalone unions
      expect(content).toContain("import type {");
      expect(content).toContain("SkillId as GlobalSkillId");
      expect(content).toContain("export type SkillId = GlobalSkillId;");
      // Should NOT contain inline skill IDs from the matrix
      expect(content).not.toContain('"web-framework-react"');
    } finally {
      // Restore to non-existent path
      Object.defineProperty(consts, "GLOBAL_INSTALL_ROOT", {
        value: "/tmp/nonexistent-global-root",
        writable: true,
      });
    }
  });

  it("includes project-only extras when global exists", async () => {
    const { CLAUDE_SRC_DIR: claudeSrc, STANDARD_FILES: files } = await import("../../../consts");
    const consts = await import("../../../consts");
    Object.defineProperty(consts, "GLOBAL_INSTALL_ROOT", { value: globalDir, writable: true });

    try {
      const globalClaudeSrc = path.join(globalDir, claudeSrc);
      await mkdir(globalClaudeSrc, { recursive: true });
      const { writeFile } = await import("fs/promises");
      await writeFile(path.join(globalClaudeSrc, files.CONFIG_TYPES_TS), "// global types");

      const projectClaudeSrc = path.join(tempDir, claudeSrc);
      await mkdir(projectClaudeSrc, { recursive: true });

      const data = makeBackgroundData({});

      await regenerateConfigTypes(tempDir, data, {
        extraSkillIds: ["acme-deploy-pipeline"],
        extraAgentNames: ["custom-reviewer"],
      });

      const configTypesPath = path.join(projectClaudeSrc, files.CONFIG_TYPES_TS);
      const content = await readFile(configTypesPath, "utf-8");

      expect(content).toContain("SkillId as GlobalSkillId");
      expect(content).toContain('"acme-deploy-pipeline"');
      expect(content).toContain('"custom-reviewer"');
    } finally {
      Object.defineProperty(consts, "GLOBAL_INSTALL_ROOT", {
        value: "/tmp/nonexistent-global-root",
        writable: true,
      });
    }
  });

  it("narrows SelectedAgentName from project config selectedAgents", async () => {
    const { CLAUDE_SRC_DIR: claudeSrc, STANDARD_FILES: files } = await import("../../../consts");
    const consts = await import("../../../consts");
    Object.defineProperty(consts, "GLOBAL_INSTALL_ROOT", { value: globalDir, writable: true });

    try {
      // Create global config-types.ts
      const globalClaudeSrc = path.join(globalDir, claudeSrc);
      await mkdir(globalClaudeSrc, { recursive: true });
      const { writeFile: fsWriteFile } = await import("fs/promises");
      await fsWriteFile(path.join(globalClaudeSrc, files.CONFIG_TYPES_TS), "// global types");

      // Create project .claude-src/ with a config that has selectedAgents
      const projectClaudeSrc = path.join(tempDir, claudeSrc);
      await mkdir(projectClaudeSrc, { recursive: true });

      const { generateConfigSource } = await import("../config-writer");
      const configContent = generateConfigSource(
        buildProjectConfig({
          selectedAgents: ["web-developer", "api-developer"],
        }),
      );
      await fsWriteFile(path.join(projectClaudeSrc, files.CONFIG_TS), configContent);

      const data = makeBackgroundData({});
      await regenerateConfigTypes(tempDir, data);

      const configTypesPath = path.join(projectClaudeSrc, files.CONFIG_TYPES_TS);
      const content = await readFile(configTypesPath, "utf-8");

      // SelectedAgentName should be narrowed to the config's selectedAgents
      expect(content).toContain(
        'export type SelectedAgentName = "web-developer" | "api-developer"',
      );
      // Should NOT fall back to AgentName
      expect(content).not.toContain("export type SelectedAgentName = AgentName");
    } finally {
      Object.defineProperty(consts, "GLOBAL_INSTALL_ROOT", {
        value: "/tmp/nonexistent-global-root",
        writable: true,
      });
    }
  });

  it("narrows ProjectAgentName to project-scoped agents from loaded config", async () => {
    const { CLAUDE_SRC_DIR: claudeSrc, STANDARD_FILES: files } = await import("../../../consts");
    const consts = await import("../../../consts");
    Object.defineProperty(consts, "GLOBAL_INSTALL_ROOT", { value: globalDir, writable: true });

    try {
      const globalClaudeSrc = path.join(globalDir, claudeSrc);
      await mkdir(globalClaudeSrc, { recursive: true });
      const { writeFile: fsWriteFile } = await import("fs/promises");
      await fsWriteFile(path.join(globalClaudeSrc, files.CONFIG_TYPES_TS), "// global types");

      const projectClaudeSrc = path.join(tempDir, claudeSrc);
      await mkdir(projectClaudeSrc, { recursive: true });

      // Config with mixed scopes: web-developer global, api-developer project
      const { generateConfigSource } = await import("../config-writer");
      const configContent = generateConfigSource(
        buildProjectConfig({
          agents: [
            ...buildAgentConfigs(["web-developer"], { scope: "global" }),
            ...buildAgentConfigs(["api-developer"], { scope: "project" }),
          ],
          selectedAgents: ["web-developer", "api-developer"],
        }),
      );
      await fsWriteFile(path.join(projectClaudeSrc, files.CONFIG_TS), configContent);

      const data = makeBackgroundData({});
      await regenerateConfigTypes(tempDir, data);

      const configTypesPath = path.join(projectClaudeSrc, files.CONFIG_TYPES_TS);
      const content = await readFile(configTypesPath, "utf-8");

      // ProjectAgentName should be narrowed to only project-scoped agent
      expect(content).toContain('export type ProjectAgentName = "api-developer"');
      // Should NOT fall back to SelectedAgentName
      expect(content).not.toContain("export type ProjectAgentName = SelectedAgentName");
      // SelectedAgentName should still include all selected agents
      expect(content).toContain(
        'export type SelectedAgentName = "web-developer" | "api-developer"',
      );
    } finally {
      Object.defineProperty(consts, "GLOBAL_INSTALL_ROOT", {
        value: "/tmp/nonexistent-global-root",
        writable: true,
      });
    }
  });

  it("falls back ProjectAgentName to SelectedAgentName when all agents are global", async () => {
    const { CLAUDE_SRC_DIR: claudeSrc, STANDARD_FILES: files } = await import("../../../consts");
    const consts = await import("../../../consts");
    Object.defineProperty(consts, "GLOBAL_INSTALL_ROOT", { value: globalDir, writable: true });

    try {
      const globalClaudeSrc = path.join(globalDir, claudeSrc);
      await mkdir(globalClaudeSrc, { recursive: true });
      const { writeFile: fsWriteFile } = await import("fs/promises");
      await fsWriteFile(path.join(globalClaudeSrc, files.CONFIG_TYPES_TS), "// global types");

      const projectClaudeSrc = path.join(tempDir, claudeSrc);
      await mkdir(projectClaudeSrc, { recursive: true });

      // Config with all global-scoped agents (simulates global init)
      const { generateConfigSource } = await import("../config-writer");
      const configContent = generateConfigSource(
        buildProjectConfig({
          agents: buildAgentConfigs(["web-developer", "web-reviewer"], { scope: "global" }),
          selectedAgents: ["web-developer", "web-reviewer"],
        }),
      );
      await fsWriteFile(path.join(projectClaudeSrc, files.CONFIG_TS), configContent);

      const data = makeBackgroundData({});
      await regenerateConfigTypes(tempDir, data);

      const configTypesPath = path.join(projectClaudeSrc, files.CONFIG_TYPES_TS);
      const content = await readFile(configTypesPath, "utf-8");

      // ProjectAgentName should fall back to SelectedAgentName (all agents are global)
      expect(content).toContain("export type ProjectAgentName = SelectedAgentName");
    } finally {
      Object.defineProperty(consts, "GLOBAL_INSTALL_ROOT", {
        value: "/tmp/nonexistent-global-root",
        writable: true,
      });
    }
  });
});
