import { describe, it, expect } from "vitest";
import { generateConfigTypesSource } from "../ts-config-types-writer";
import { createMockSkill, createMockMatrix, createMockCategory } from "../../__tests__/helpers";
import type { AgentName, CategoryDefinition, Subcategory } from "../../../types";

describe("generateConfigTypesSource", () => {
  it("includes auto-generated header comment", () => {
    const matrix = createMockMatrix({});
    const source = generateConfigTypesSource(matrix, []);
    expect(source).toContain("// AUTO-GENERATED by agentsinc — DO NOT EDIT");
  });

  it("generates SkillId union from matrix skills", () => {
    const matrix = createMockMatrix({
      "web-framework-react": createMockSkill("web-framework-react", "web-framework"),
      "api-framework-hono": createMockSkill("api-framework-hono", "api-api"),
    });
    const source = generateConfigTypesSource(matrix, []);
    expect(source).toContain('"api-framework-hono"');
    expect(source).toContain('"web-framework-react"');
    expect(source).toContain("export type SkillId =");
  });

  it("generates AgentName union from provided agent names", () => {
    const matrix = createMockMatrix({});
    const agentNames: AgentName[] = ["web-developer", "api-developer"];
    const source = generateConfigTypesSource(matrix, agentNames);
    expect(source).toContain('"api-developer"');
    expect(source).toContain('"web-developer"');
    expect(source).toContain("export type AgentName =");
  });

  it("sorts union members alphabetically", () => {
    const matrix = createMockMatrix({
      "web-styling-scss-modules": createMockSkill("web-styling-scss-modules", "web-styling"),
      "api-framework-hono": createMockSkill("api-framework-hono", "api-api"),
      "web-framework-react": createMockSkill("web-framework-react", "web-framework"),
    });
    const agentNames: AgentName[] = ["web-developer", "api-developer", "cli-developer"];
    const source = generateConfigTypesSource(matrix, agentNames);

    // Verify skill IDs are sorted (api before web)
    const skillIdLine = source.split("\n").find((l) => l.startsWith("export type SkillId"));
    expect(skillIdLine).toBeDefined();
    const apiIdx = source.indexOf('"api-framework-hono"');
    const webFrameworkIdx = source.indexOf('"web-framework-react"');
    const webStylingIdx = source.indexOf('"web-styling-scss-modules"');
    expect(apiIdx).toBeLessThan(webFrameworkIdx);
    expect(webFrameworkIdx).toBeLessThan(webStylingIdx);

    // Verify agent names are sorted
    const apiDevIdx = source.indexOf('"api-developer"');
    const cliDevIdx = source.indexOf('"cli-developer"');
    const webDevIdx = source.indexOf('"web-developer"');
    expect(apiDevIdx).toBeLessThan(cliDevIdx);
    expect(cliDevIdx).toBeLessThan(webDevIdx);
  });

  it("generates Domain type from matrix categories", () => {
    const categories = {
      "web-framework": createMockCategory("web-framework" as Subcategory, "Framework", {
        domain: "web",
      }),
      "api-api": createMockCategory("api-api" as Subcategory, "API", {
        domain: "api",
      }),
    } as Record<Subcategory, CategoryDefinition>;

    const matrix = createMockMatrix({}, { categories });
    const source = generateConfigTypesSource(matrix, []);
    expect(source).toContain('export type Domain = "api" | "web";');
  });

  it("generates Subcategory union from matrix category keys", () => {
    const categories = {
      "web-framework": createMockCategory("web-framework" as Subcategory, "Framework", {
        domain: "web",
      }),
      "api-api": createMockCategory("api-api" as Subcategory, "API", {
        domain: "api",
      }),
      "web-styling": createMockCategory("web-styling" as Subcategory, "Styling", {
        domain: "web",
      }),
    } as Record<Subcategory, CategoryDefinition>;

    const matrix = createMockMatrix({}, { categories });
    const source = generateConfigTypesSource(matrix, []);
    expect(source).toContain(
      'export type Subcategory = "api-api" | "web-framework" | "web-styling";',
    );
  });

  it("falls back to string for empty subcategories", () => {
    const matrix = createMockMatrix(
      {},
      { categories: {} as Record<Subcategory, CategoryDefinition> },
    );
    const source = generateConfigTypesSource(matrix, []);
    expect(source).toContain("export type Subcategory = string;");
  });

  it("generates InstallMode type", () => {
    const matrix = createMockMatrix({});
    const source = generateConfigTypesSource(matrix, []);
    expect(source).toContain('export type InstallMode = "local" | "plugin";');
  });

  it("generates SkillAssignment type with string and object forms", () => {
    const matrix = createMockMatrix({});
    const source = generateConfigTypesSource(matrix, []);
    expect(source).toContain(
      "export type SkillAssignment = SkillId | { id: SkillId; preloaded: boolean };",
    );
  });

  it("generates StackAgentConfig type with Subcategory keys", () => {
    const matrix = createMockMatrix({});
    const source = generateConfigTypesSource(matrix, []);
    expect(source).toContain(
      "export type StackAgentConfig = Partial<Record<Subcategory, SkillAssignment>>;",
    );
  });

  it("generates ProjectConfig interface with AgentName stack keys", () => {
    const matrix = createMockMatrix({});
    const source = generateConfigTypesSource(matrix, []);
    expect(source).toContain("export interface ProjectConfig {");
    expect(source).toContain("name: string;");
    expect(source).toContain("agents: AgentName[];");
    expect(source).toContain("skills: SkillId[];");
    expect(source).toContain("installMode?: InstallMode;");
    expect(source).toContain("stack?: Partial<Record<AgentName, StackAgentConfig>>;");
    expect(source).toContain("domains?: Domain[];");
    expect(source).toContain("selectedAgents?: AgentName[];");
    expect(source).toContain("source?: string;");
    expect(source).toContain("marketplace?: string;");
    expect(source).toContain("agentsSource?: string;");
    expect(source).toContain("author?: string;");
    expect(source).toContain("description?: string;");
  });

  it("falls back to string for empty skills", () => {
    const matrix = createMockMatrix({});
    const source = generateConfigTypesSource(matrix, []);
    expect(source).toContain("export type SkillId = string;");
  });

  it("falls back to string for empty agents", () => {
    const matrix = createMockMatrix({
      "web-framework-react": createMockSkill("web-framework-react", "web-framework"),
    });
    const source = generateConfigTypesSource(matrix, []);
    expect(source).toContain("export type AgentName = string;");
  });

  it("falls back to string for empty domains", () => {
    const matrix = createMockMatrix(
      { "web-framework-react": createMockSkill("web-framework-react", "web-framework") },
      { categories: {} as Record<Subcategory, CategoryDefinition> },
    );
    const source = generateConfigTypesSource(matrix, []);
    expect(source).toContain("export type Domain = string;");
  });

  it("uses single-line format for 5 or fewer union members", () => {
    const matrix = createMockMatrix({
      "api-framework-hono": createMockSkill("api-framework-hono", "api-api"),
      "web-framework-react": createMockSkill("web-framework-react", "web-framework"),
    });
    const source = generateConfigTypesSource(matrix, []);
    // 2 skills = single-line union
    expect(source).toContain('export type SkillId = "api-framework-hono" | "web-framework-react";');
  });

  it("uses multi-line format for 6 or more union members", () => {
    const skills: Record<string, ReturnType<typeof createMockSkill>> = {};
    const ids = [
      "api-database-drizzle",
      "api-framework-hono",
      "web-framework-react",
      "web-framework-vue-composition-api",
      "web-state-zustand",
      "web-styling-scss-modules",
    ] as const;
    for (const id of ids) {
      skills[id] = createMockSkill(id, "web-framework");
    }
    const matrix = createMockMatrix(skills);
    const source = generateConfigTypesSource(matrix, []);
    // 6 skills = multi-line union with leading pipes
    expect(source).toContain('  | "api-database-drizzle"');
    expect(source).toContain('  | "web-styling-scss-modules"');
  });
});
